### ISSUE TITLE
Repo FileNotFoundError/Log FileNotFoundError

### ISSUE THREAD

**Issue by i4never** [polyaxon/polyaxon#103]
My deployment is on aws kubernetes cluster. The experiment running failed due to FileNotExist. Here's the logs for scheduler container:
`[2018-04-20 02:49:05,979: INFO/MainProcess] Received task: experiments_build[f731be9d-3efd-43da-a36b-348a3292165d]  ETA:[2018-04-20 02:49:06.951478+00:00] 
[2018-04-20 02:49:07,121: ERROR/ForkPoolWorker-2] Celery Task Failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/polyaxon/polyaxon/experiments/tasks.py", line 61, in build_experiment
    status = experiments_builder.build_experiment(experiment)
  File "/polyaxon/polyaxon/dockerizer/builders/experiments.py", line 117, in build_experiment
    env_vars=experiment_spec.run_exec.env_vars)
  File "/polyaxon/polyaxon/dockerizer/builders/experiments.py", line 46, in __init__
    dockerfile_name=dockerfile_name)
  File "/polyaxon/polyaxon/dockerizer/builders/base.py", line 47, in __init__
    self.build_repo_path = self.create_tmp_repo()
  File "/polyaxon/polyaxon/dockerizer/builders/base.py", line 61, in create_tmp_repo
    return copy_to_tmp_dir(self.repo_path, os.path.join(self.image_tag, self.folder_name))
  File "/polyaxon/polyaxon/libs/paths.py", line 48, in copy_to_tmp_dir
    shutil.copytree(path, tmp_path)
  File "/usr/lib/python3.5/shutil.py", line 303, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/repos/root/quick-start/quick-start'
`
I check the file in scheduler container and find the code path is `/repos/quick-start/quick-start` instead of `/repos/root/quick-start/quick-start`.

After I create `root` dir under `/repos` and move files into this path, the experiment status is 'starting' and the scheduler keeps printing:
`
[2018-04-20 03:35:30,857: INFO/ForkPoolWorker-2] Publishing log event for task: None.None, root.q-s.8
INFO 2018-04-20 03:35:30,977 publisher 12 139964421228288 Publishing log event for task: None.None, root.q-s.8
[2018-04-20 03:35:30,977: INFO/ForkPoolWorker-2] Publishing log event for task: None.None, root.q-s.8
INFO 2018-04-20 03:35:31,109 publisher 12 139964421228288 Publishing log event for task: None.None, root.q-s.8
[2018-04-20 03:35:31,109: INFO/ForkPoolWorker-2] Publishing log event for task: None.None, root.q-s.8
INFO 2018-04-20 03:35:31,234 publisher 12 139964421228288 Publishing log event for task: None.None, root.q-s.8
[2018-04-20 03:35:31,234: INFO/ForkPoolWorker-2] Publishing log event for task: None.None, root.q-s.8
`

And the log for worker container shows it can't find file `/logs/root/quick-start/independents/8` (This is the 8th experiment I run). Here's the log:
`
[2018-04-20 03:34:26,919: ERROR/ForkPoolWorker-1] Celery Task Failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/polyaxon/polyaxon/events/tasks.py", line 92, in handle_events_job_logs
    log_handler = logging.FileHandler(log_path)
  File "/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/logs/root/quick-start/independents/8'

`
So I create the dir `/logs/root/quick-start/indenpendents` and the experiment seems to work fine. However, I still can't get any log information from cli or dashboard. I can only get the result of this experiment by check the log file in worker container.

**Comment by mouradmourafiq** [comment]
Ok I really need to investigate this further because it seems very related to #98

**Comment by i4never** [comment]
@mouradmourafiq 
I don't think this issue is related to #98 because the upload is successful. What's wrong is the file path. Does username recently become part of the `repo_path` ?
