### ISSUE TITLE
Resources pods crashing and can't recover -- possibly triggered under load?

### ISSUE THREAD

**Issue by honnibal** [polyaxon/polyaxon#117]
In some situations the resources pods crash and apparently can't recover. This happened when I loaded the Tensorflow or PyTorch images without a GPU attached, and when I ran a job that I think exceeded resource requirements.

Output of `kubectl --namespace polyaxon logs polyaxon-polyaxon-resources-4grwd`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "clusters_cluster" does not exist
LINE 1: ...er"."uuid", "clusters_cluster"."version_api" FROM "clusters_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "polyaxon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/polyaxon/polyaxon/events/management/commands/monitor_resources.py", line 26, in handle
    node = self.get_node()
  File "/polyaxon/polyaxon/events/management/commands/monitor_resources.py", line 17, in get_node
    cluster = Cluster.load()
  File "/polyaxon/polyaxon/clusters/models.py", line 31, in load
    obj = cls.objects.get(pk=1)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1066, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/raven/contrib/django/client.py", line 123, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "clusters_cluster" does not exist
LINE 1: ...er"."uuid", "clusters_cluster"."version_api" FROM "clusters_...
                                                             ^```

**Comment by mouradmourafiq** [comment]
Hi @honnibal I think the issue that you had is related to a database failure. So most probably you ran a job or some jobs that crashed the db and/or other services.

The default configuration is not meant to be for a production environment. But I think I will at least change the default values to activate the database persistence by default so that in case of a crash, the user does not lose the data.

**Comment by honnibal** [comment]
@mouradmourafiq Thanks! Which config should I be editing to change this? I think I'm a little confused about the architecture.

When I log into the dashboard, that's the Django app that's reporting the crash above, right? I figured the dashboard was mostly a reports layer, although it also does the user management. But does the Django app also own the database that provides the record of what experiments were run, what the results were, etc?

**Comment by mouradmourafiq** [comment]
Hi @honnibal, the [config](https://docs.polyaxon.com/installation/deploy_polyaxon/#configuration) is where you specify how to deploy Polyaxon, for example in the case of the tutorial it's this [file](https://github.com/polyaxon/polyaxon-examples/blob/master/gke/polyaxon-config.yml).

This file can have many [options](https://docs.polyaxon.com/reference_polyaxon_helm/) to override the default helm values Polyaxon uses.

For instance you can, change the resources you want to allocate to the api or postgres, or rabbitmq. To add persistence to the database you need to add this to the config file:
```yaml
postgresql:
  persistence:
      enabled: true
      size: 5Gi
```

Regarding your second question about the architecture, the app leverages Django for handling the data model, apis, and anything asynchronous is done with workers based on celery, and you can scale the and these workers (in terms of resources and also in terms of number of pods) by changing also the configuration.

The app tracks all experiments and persist the values to the database, that's why if the postgres pod fails and there's no persistence you lose the experiments, but you will not lose the outputs and logs of your experiments, because they will be in the volumes. By making the database persistent you will not lose the database as well if it crashes, it will just be down while kubernetes restart a new pod and assign the db volume to it. The database is also important because it tracks which project these experiments belong to, the code version and commits, who started them and when, and for how long, the metrics if you decide to report them back to the platform, and many other meta data. More data will be displayed on the dashboard.

The data, outputs, and logs are saved to the volumes specified, in the case of the tutorial it was the nfs server, and again there are many ways you can do that if you want to scale it or make it faster, for example the resources allocated to the instance of the nfs server, or you can create a server for each volume managed.

Let me know if you have more questions, I am happy to provide more insight about the architecture.

**Comment by honnibal** [comment]
Ah, thanks! The `postgres` block is missing from the docs. I think persistence is probably a good default setting, too.

**Comment by honnibal** [comment]
Up and running!
