### ISSUE TITLE
Error for integer environment variables

### ISSUE THREAD

**Issue by tobigue** [polyaxon/polyaxon#1207]
When setting environment variables with integer values via a polyaxonfile the run fails with the following Error:

```
Kubernetes manager could not start the operation.
error: ApiException()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/coredb/scheduler/manager.py", line 197, in runs_start
    manager.start(
  File "/usr/local/lib/python3.8/site-packages/polyaxon/agents/manager.py", line 40, in start
    Spawner(namespace=namespace, in_cluster=in_cluster).create(
  File "/usr/local/lib/python3.8/site-packages/polyaxon/agents/spawners/spawner.py", line 38, in create
    return self.k8s_manager.create_custom_object(
  File "/usr/local/lib/python3.8/site-packages/polyaxon/k8s/manager.py", line 307, in create_custom_object
    resp = self.k8s_custom_object_api.create_namespaced_custom_object(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 225, in create_namespaced_custom_object
    return self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 344, in create_namespaced_custom_object_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 274, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict(...)
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation.core.polyaxon.com \"plx-operation-52a2c16c16d64759be4d1cb7fa0cb4cd\" is invalid: batchJobSpec.template.spec.containers.env.value: Invalid value: \"integer\": batchJobSpec.template.spec.containers.env.value in body must be of type string: \"integer\"","reason":"Invalid","details":{"name":"plx-operation-52a2c16c16d64759be4d1cb7fa0cb4cd","group":"core.polyaxon.com","kind":"Operation","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"integer\": batchJobSpec.template.spec.containers.env.value in body must be of type string: \"integer\"","field":"batchJobSpec.template.spec.containers.env.value"}]},"code":422}
```

Polyaxonfile to reproduce the error:

```
version: 1.1
kind: component
name: simple-experiment
description: Minimum information to run this TF.Keras example
tags: [examples]
run:
  kind: job
  init:
  - git: {url: "https://github.com/polyaxon/polyaxon-quick-start"}
  container:
    image: polyaxon/polyaxon-quick-start
    workingDir: "{{ globals.artifacts_path }}/polyaxon-quick-start"
    command: [python3, model.py]
    env:
      - name: POLYAXON_RUN_OUTPUTS_PATH
        value: "{{ globals.run_outputs_path }}"
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: PYTHONHASHSEED
        value: "0"
```

Even though the values are defined as string in the polyaxonfile, they show up as integer in the "Compiled Specification" tab.

Version: Polyaxon CE v1.5.0

**Comment by mouradmourafiq** [comment]
Thank you for reporting this, we will add it to v1.5.1. 
We are planning the release today, otherwise it will be available tomorrow.
