### ISSUE TITLE
Logs not found - Polyaxon streams returns - HTTP_500_INTERNAL_SERVER_ERROR.

### ISSUE THREAD

**Issue by samuelbr** [polyaxon/polyaxon#1235]
### Describe the bug

Logs are empty (message: Logs not found) in some jobs. Request which loads logs has status code 500.

Streams container (image: polyaxon/polyaxon-streams:1.6.0) contains these logs:

<pre>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 172, in __call__
    response = await self.handler(request, exc)
  File "/usr/local/lib/python3.8/site-packages/polyaxon/streams/app/endpoints.py", line 402, in server_error
    raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR)
starlette.exceptions.HTTPException
[2021-02-26 12:16:12 +0000] [64] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 582, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 243, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 54, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/polyaxon/streams/app/endpoints.py", line 106, in get_logs
    operation_logs, last_file, files = await get_archived_operation_logs(
  File "/usr/local/lib/python3.8/site-packages/polyaxon/streams/controllers/logs.py", line 86, in get_archived_operation_logs
    logs = await read_logs_file(logs_path)
  File "/usr/local/lib/python3.8/site-packages/polyaxon/streams/controllers/logs.py", line 65, in read_logs_file
    return V1Logs.read_csv(contents).logs
  File "/usr/local/lib/python3.8/site-packages/polyaxon/polyboard/logging/schemas.py", line 141, in read_csv
    df = pd.read_csv(
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 860, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 929, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 916, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2071, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 5 fields in line 42, saw 6
</pre>

Polyaxon log file:
<pre>
...
2021-02-26 12:05:31.460424+00:00|worker1|plx-operation-dc016815081746d7a462af1d1df1b72a-jtsdd|polyaxon-main|{"_":"\/opt\/keras-retinanet\/.eggs\/numpy-1.20.1-py3.8-linux-x86_64.egg\/numpy\/core\/include\/numpy\/npy_1_7_deprecated_api.h:17:2: warning: #warning \"Using deprecated NumPy API, disable it with \" \"#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\" [-Wcpp]"}
2021-02-26 12:05:31.460434+00:00|worker1|plx-operation-dc016815081746d7a462af1d1df1b72a-jtsdd|polyaxon-main|{"_":"   17 | #warning \"Using deprecated NumPy API, disable it with \" \\"}
2021-02-26 12:05:31.460443+00:00|worker1|plx-operation-dc016815081746d7a462af1d1df1b72a-jtsdd|polyaxon-main|{"_":"      |  ^~~~~~~"}
2021-02-26 12:05:32.808749+00:00|worker1|plx-operation-dc016815081746d7a462af1d1df1b72a-jtsdd|polyaxon-main|{"_":"creating build\/lib.linux-x86_64-3.8"}
...
</pre>

I guess that problem is unescaped pipe *|*  in value colum.

### Expected behavior

UI loads logs.

### Environment

Polyaxon installed with Helm on K8s cluster. 
Polyaxon version: v1.6.0

**Comment by polyaxon-team** [comment]
Thank you for reporting, we released [v1.6.1](https://github.com/polyaxon/polyaxon/blob/master/releases/1-6.md#v161) yesterday with a fix.

`helm repo update` and then just deploy the new patch release.

**Comment by polyaxon-team** [comment]
This might be another issue.

**Comment by polyaxon-team** [comment]
Just checked, v1.6.1 will not raise an error for the file snippet you shared, it ignores those lines with the pipe. We will keep this issue to be fixed in next releases.

**Comment by samuelbr** [comment]
Thanks, I upgraded to v1.6.1 and it helps.
