### ISSUE TITLE
Upload flag using Polyaxon cli breaks run

### ISSUE THREAD

**Issue by minaadel** [polyaxon/polyaxon#1269]
### Describe the bug
I am unable to use the `-u` flag to upload files from local directories to runs in combination with `polyaxon run`. 
The command fails to execute with the following stack trace
```
You can view this run on Polyaxon UI: XX.XXX.XXX.XXX:31811/ui/default/test/runs/8d24b0662ed14002b5fd30a1d5d0dfb2/
[================================] 0/3221 - 00:00:02
Traceback (most recent call last):
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\http\client.py", line 956, in send
    self.connect()
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000230FAC6EAC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='streams', port=80): Max retries exceeded with url: /v1/polyaxon/default/test/runs/8d24b0662ed14002b5fd30a1d5d0dfb2/artifacts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FAC6EAC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user.profile\AppData\Local\Programs\Python\Python37\Scripts\polyaxon.exe\__main__.py", line 9, in <module>
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\logger.py", line 85, in clean_outputs_wrapper
    return fn(*args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\cli\run.py", line 351, in run
    eager=eager,
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\cli\executor\platform.py", line 137, in run
    run_upload, path_to=upload_to, path_from=upload_from, sync_failure=True
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\logger.py", line 85, in clean_outputs_wrapper
    return fn(*args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\cli\operations.py", line 999, in upload
    relative_to=path_from,
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\client\decorators\client_handler.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\client\run.py", line 929, in upload_artifacts_dir
    relative_to=relative_to,
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\client\decorators\client_handler.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\client\run.py", line 966, in upload_artifacts
    relative_to=relative_to,
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\stores\polyaxon_store.py", line 297, in upload_dir
    url, files=files, files_size=files_size, json_data=json_data
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\polyaxon\stores\polyaxon_store.py", line 160, in upload
    timeout=timeout,
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\user.profile\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='streams', port=80): Max retries exceeded with url: /v1/polyaxon/default/test/runs/8d24b0662ed14002b5fd30a1d5d0dfb2/artifacts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FAC6EAC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```
### To reproduce
This is my microk8s status
```
$ microk8s kubectl get svc --all-namespaces
NAMESPACE            NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
container-registry   registry                       NodePort    10.152.183.244   <none>        5000:32000/TCP           137m
default              kubernetes                     ClusterIP   10.152.183.1     <none>        443/TCP                  138m
kube-system          dashboard-metrics-scraper      ClusterIP   10.152.183.193   <none>        8000/TCP                 137m
kube-system          elasticsearch-logging          ClusterIP   10.152.183.138   <none>        9200/TCP                 137m
kube-system          heapster                       ClusterIP   10.152.183.126   <none>        80/TCP                   137m
kube-system          kibana-logging                 ClusterIP   10.152.183.180   <none>        5601/TCP                 137m
kube-system          kube-dns                       ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   138m
kube-system          kubernetes-dashboard           ClusterIP   10.152.183.250   <none>        443/TCP                  137m
kube-system          metrics-server                 ClusterIP   10.152.183.233   <none>        443/TCP                  137m
kube-system          monitoring-grafana             ClusterIP   10.152.183.212   <none>        80/TCP                   137m
kube-system          monitoring-influxdb            ClusterIP   10.152.183.16    <none>        8083/TCP,8086/TCP        137m
kube-system          tiller-deploy                  ClusterIP   10.152.183.167   <none>        44134/TCP                136m
polyaxon             polyaxon-polyaxon-api          NodePort    10.152.183.19    <none>        80:31811/TCP             127m
polyaxon             polyaxon-polyaxon-gateway      NodePort    10.152.183.226   <none>        80:31833/TCP             127m
polyaxon             polyaxon-polyaxon-streams      NodePort    10.152.183.222   <none>        80:31822/TCP             127m
polyaxon             polyaxon-postgresql            ClusterIP   10.152.183.232   <none>        5432/TCP                 127m
polyaxon             polyaxon-postgresql-headless   ClusterIP   None             <none>        5432/TCP                 127m

```

```
C:\Users\mina.nessiem\Development\mnist_polyaxon_1.1.6>polyaxon config show

Client config:

---------------------------------  --------------------
POLYAXON_HOST                      XX.XXX.XXX.XXX:31811
POLYAXON_API_VERSION               v1
POLYAXON_DEBUG                     False
POLYAXON_AUTHENTICATION_TYPE       Token
POLYAXON_IS_MANAGED                False
POLYAXON_IS_OFFLINE                False
POLYAXON_IS_OPS                    False
POLYAXON_K8S_IN_CLUSTER            False
POLYAXON_NO_OP                     False
POLYAXON_TIMEOUT                   20.0
POLYAXON_TRACKING_TIMEOUT          1.0
POLYAXON_TIME_ZONE
POLYAXON_WATCH_INTERVAL            5
POLYAXON_INTERVAL                  5.0
POLYAXON_VERIFY_SSL                True
POLYAXON_ARCHIVE_ROOT              /tmp/plx/archives
POLYAXON_NO_API                    False
POLYAXON_DISABLE_ERRORS_REPORTING  False
---------------------------------  --------------------

CLI config:

Version 1.8.0
-------  --------------------------------
KEY      bc9354f6d58e542cbe49cc4bf2cfc29e
VERSION  1.8.0
DIST     ce
-------  --------------------------------

User config:

------------
USERNAME
EMAIL
NAME
ORGANIZATION
------------
```

I am otherwise capable of executing runs using the Polyaxon CLI

### Expected behavior
I would like to be able to upload a locally edited python script as part of my experiement run and have it execute. I am currently forced to build the scripts I wish to run into my docker images in order to execute them...

### Environment
The behavior was tested with both polyaxon server 1.8.0 and 1.7.6
and the polyaxon cli with both polyaxon cli version 1.8.0 and 1.7.6

**Comment by mouradmourafiq** [comment]
Closing this issue, I should have checked the logs more carefully:

```
polyaxon             polyaxon-polyaxon-api          NodePort    10.152.183.19    <none>        80:31811/TCP             127m
polyaxon             polyaxon-polyaxon-gateway      NodePort    10.152.183.226   <none>        80:31833/TCP             127m
polyaxon             polyaxon-polyaxon-streams      NodePort    10.152.183.222   <none>        80:31822/TCP             127m
```

```
C:\Users\mina.nessiem\Development\mnist_polyaxon_1.1.6>polyaxon config show

Client config:

---------------------------------  --------------------
POLYAXON_HOST                      XX.XXX.XXX.XXX:31811
```

`31811` confirms that you are exposing the API and not the gateway.
