### ISSUE TITLE
 polyaxon experiment outputs fails: outputs() missing 1 required positional argument: 'ctx'

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#132]
### Describe the bug

`polyaxon experiment outputs` both in an experiment and without anyone

```
Traceback (most recent call last):
  File "/pythonenv/iris3/bin/polyaxon", line 11, in <module>
    sys.exit(cli())
  File "/pythonenv/iris3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/pythonenv/iris3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "pythonenv/iris3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/pythonenv/iris3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/pythonenv/iris3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/pythonenv/iris3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/pythonenv/iris3/lib/python3.6/site-packages/polyaxon_cli/logger.py", line 54, in clean_outputs_wrapper
    raise e
  File "/pythonenv/iris3/lib/python3.6/site-packages/polyaxon_cli/logger.py", line 48, in clean_outputs_wrapper
    return fn(*args, **kwargs)
TypeError: outputs() missing 1 required positional argument: 'ctx'
```

**Comment by mouradmourafiq** [comment]
@jorgemf yes this command is not there at the current release, will be in the next release though 👍

**Comment by mouradmourafiq** [comment]
This was added since 0.1.1, I forgot to update this issue :)
