### ISSUE TITLE
polyaxon-api times out

### ISSUE THREAD

**Issue by ningyuuu** [polyaxon/polyaxon#171]
### Describe the bug
Hi! This is my first attempt with Kubernetes, and while attempting to deploy the project on a minikube instance, it seems that my API server always times out. It seems that the server is highly unresponsive and unstable - I could log in, but the service stopped responding immediately after. According to the logs, sometimes `server nginx start` will fail, but it seems like that is not the cause.

Minikube is running on Ubuntu 16.04, `vm-driver=none`. Not sure if I did something wrong, thanks for your help!

config.yaml
```
isMinikube: true
rbac:
  enabled: false
ingress:
  enabled: false
serviceType: LoadBalancer
```

Kubectl describe:
```
Name:           polyaxon-polyaxon-api-85644764bd-pljbn
Namespace:      polyaxon
Node:           minikube/172.27.141.142
Start Time:     Fri, 17 Aug 2018 11:29:55 +0800
Labels:         app=polyaxon-polyaxon-api
                pod-template-hash=4120032068
                release=polyaxon
                role=polyaxon-api
                type=polyaxon-core
Annotations:    <none>
Status:         Running
IP:             172.17.0.16
Controlled By:  ReplicaSet/polyaxon-polyaxon-api-85644764bd
Containers:
  polyaxon-api:
    Container ID:   docker://ee115b33f26af5abda88e2e6d9e6dcf9faaa85b37952fca6db64e589add54d92
    Image:          polyaxon/polyaxon-api:0.1.8
    Image ID:       docker-pullable://polyaxon/polyaxon-api@sha256:950aeb2f7e31fe5436154e32ae63890ded4a4c214f23ace8093d473884825add
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 17 Aug 2018 11:36:50 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Fri, 17 Aug 2018 11:29:57 +0800
      Finished:     Fri, 17 Aug 2018 11:36:49 +0800
    Ready:          True
    Restart Count:  1
    Requests:
      cpu:      128m
      memory:   300Mi
    Liveness:   http-get http://:80/_health/ delay=100s timeout=2s period=30s #success=1 #failure=10
    Readiness:  http-get http://:80/_health/ delay=150s timeout=2s period=30s #success=1 #failure=30
    Environment Variables from:
      polyaxon-polyaxon-config  ConfigMap  Optional: false
      polyaxon-polyaxon-secret  Secret     Optional: false
    Environment:
      POLYAXON_K8S_NODE_NAME:         (v1:spec.nodeName)
      POLYAXON_RABBITMQ_PASSWORD:    <set to the key 'rabbitmq-password' in secret 'polyaxon-rabbitmq'>    Optional: false
      POLYAXON_DB_PASSWORD:          <set to the key 'postgres-password' in secret 'polyaxon-postgresql'>  Optional: false
      POLYAXON_PERSISTENCE_OUTPUTS:  {"outputs":{"hostPath":"/outputs","mountPath":"/outputs"}}
      POLYAXON_PERSISTENCE_DATA:     {"data":{"hostPath":"/data","mountPath":"/data"}}
      POLYAXON_PERSISTENCE_LOGS:     {"existingClaim":null,"hostPath":"/logs","mountPath":"/logs"}
      POLYAXON_PERSISTENCE_UPLOAD:   {"existingClaim":null,"hostPath":"/tmp/upload","mountPath":"/upload"}
      POLYAXON_PERSISTENCE_REPOS:    {"existingClaim":null,"hostPath":"/repos","mountPath":"/repos"}
    Mounts:
      /logs from logs (rw)
      /outputs from outputs (rw)
      /repos from repos (rw)
      /upload from upload (rw)
      /var/run/docker.sock from docker (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from polyaxon-polyaxon-serviceaccount-token-x7wrv (ro)
  polyaxon-streams:
    Container ID:   docker://db6a0d8e17e26313282a34bd77eb6fb5011495c6cb536f0c09af5b0ec760f5a4
    Image:          polyaxon/polyaxon-streams:0.1.8
    Image ID:       docker-pullable://polyaxon/polyaxon-streams@sha256:50873398313b544a57f25d8e54fe2a308d85ab04da3cf7bbbbe874bf361f2395
    Port:           1337/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 17 Aug 2018 11:29:57 +0800
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment Variables from:
      polyaxon-polyaxon-config  ConfigMap  Optional: false
      polyaxon-polyaxon-secret  Secret     Optional: false
    Environment:
      POLYAXON_K8S_NODE_NAME:       (v1:spec.nodeName)
      POLYAXON_RABBITMQ_PASSWORD:  <set to the key 'rabbitmq-password' in secret 'polyaxon-rabbitmq'>    Optional: false
      POLYAXON_DB_PASSWORD:        <set to the key 'postgres-password' in secret 'polyaxon-postgresql'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from polyaxon-polyaxon-serviceaccount-token-x7wrv (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  logs:
    Type:          HostPath (bare host directory volume)
    Path:          /logs
    HostPathType:
  outputs:
    Type:          HostPath (bare host directory volume)
    Path:          /outputs
    HostPathType:
  repos:
    Type:          HostPath (bare host directory volume)
    Path:          /repos
    HostPathType:
  upload:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/upload
    HostPathType:
  docker:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:
  polyaxon-polyaxon-serviceaccount-token-x7wrv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  polyaxon-polyaxon-serviceaccount-token-x7wrv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              14m                default-scheduler  Successfully assigned polyaxon-polyaxon-api-85644764bd-pljbn to miniku
be
  Normal   SuccessfulMountVolume  14m                kubelet, minikube  MountVolume.SetUp succeeded for volume "logs"
  Normal   SuccessfulMountVolume  14m                kubelet, minikube  MountVolume.SetUp succeeded for volume "outputs"
  Normal   SuccessfulMountVolume  14m                kubelet, minikube  MountVolume.SetUp succeeded for volume "docker"
  Normal   SuccessfulMountVolume  14m                kubelet, minikube  MountVolume.SetUp succeeded for volume "upload"
  Normal   SuccessfulMountVolume  14m                kubelet, minikube  MountVolume.SetUp succeeded for volume "repos"
  Normal   SuccessfulMountVolume  14m                kubelet, minikube  MountVolume.SetUp succeeded for volume "polyaxon-polyaxon-serviceaccou
nt-token-x7wrv"
  Normal   Pulled                 14m                kubelet, minikube  Container image "polyaxon/polyaxon-api:0.1.8" already present on machi
ne
  Normal   Created                14m                kubelet, minikube  Created container
  Normal   Started                14m                kubelet, minikube  Started container
  Normal   Pulled                 14m                kubelet, minikube  Container image "polyaxon/polyaxon-streams:0.1.8" already present on m
achine
  Normal   Created                14m                kubelet, minikube  Created container
  Normal   Started                14m                kubelet, minikube  Started container
  Warning  Unhealthy              8m (x8 over 12m)   kubelet, minikube  Liveness probe failed: Get http://172.17.0.16:80/_health/: net/http: r
equest canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy              4m (x11 over 11m)  kubelet, minikube  Readiness probe failed: Get http://172.17.0.16:80/_health/: net/http:
request canceled (Client.Timeout exceeded while awaiting headers)
```

Pod logs:
```
Running...
mkdir: cannot create directory ‘/polyaxon/logs’: File exists
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
 * nginx is not running
 * Restarting nginx nginx
   ...done.
 * nginx is running
[uWSGI] getting INI configuration from web/uwsgi.nginx.ini
*** Starting uWSGI 2.0.17 (64bit) on [Fri Aug 17 03:31:19 2018] ***
compiled with version: 5.4.0 20160609 on 13 August 2018 16:43:19
os: Linux-4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018
nodename: polyaxon-polyaxon-api-85644764bd-pljbn
machine: x86_64
clock source: unix
detected number of CPU cores: 12
current working directory: /polyaxon
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /polyaxon/web/..
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /polyaxon/web/../web/polyaxon.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1752670
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 425960 bytes (415 KB) for 4 cores
*** Operational MODE: preforking ***
added /polyaxon/web/../polyaxon/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1752670 pid: 99 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 99)
spawned uWSGI worker 1 (pid: 116, cores: 1)
spawned uWSGI worker 2 (pid: 117, cores: 1)
spawned uWSGI worker 3 (pid: 118, cores: 1)
spawned uWSGI worker 4 (pid: 119, cores: 1)
/usr/local/lib/python3.5/dist-packages/raven/utils/compat.py:216: Warning: We detected the use of uwsgi with disabled threads.  This will cause issues with the transport you are trying to use.  Please enable threading for uwsgi.  (Enable the "enable-threads" flag).
  warn(Warning('We detected the use of uwsgi with disabled threads.  '
ERROR 2018-08-17 03:32:07,966 exception 117 140498595825408 Internal Server Error: /_health/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "polyaxon-postgresql" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 29, in inner
    with self._recreate_cm():
  File "/usr/local/lib/python3.5/dist-packages/django/db/transaction.py", line 147, in __enter__
    if not connection.get_autocommit():
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 378, in get_autocommit
    self.ensure_connection()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "polyaxon-postgresql" to address: Temporary failure in name resolution
```

**Comment by ningyuuu** [comment]
20 minutes later, it started working. Thanks, closing this.

**Comment by jorgemf** [comment]
@ningyuuu it seems there is not network installed in the cluster. Try another version of minikube or try this: https://github.com/kubernetes/minikube/issues/2302#issuecomment-394345502

**Comment by mouradmourafiq** [comment]
@ningyuuu Try to enable `coredns` addon and see if it works. If you are using minikube with kubernetes version `1.10` then you might need to do some tweaking to get the networking to work correctly, otherwise, you can try `1.9.4`, at least it's the version I use for CI and it works.
