### ISSUE TITLE
JSON error for webhooks

### ISSUE THREAD

**Issue by engapa** [polyaxon/polyaxon#180]
### Describe the bug

I tried to notify an experiment execution to our own rest api, this is a webhook really. 
In logs we found an unexpected exception:

```
 textPayload:  "Traceback (most recent call last):
  File "/polyaxon/polyaxon/action_manager/action.py", line 72, in execute
    result = cls._execute(data=data, config=config)
  File "/polyaxon/polyaxon/action_manager/actions/webhooks/webhook.py", line 98, in _execute
    safe_request(url=web_hook['url'], method=web_hook['method'], json=data)
  File "/polyaxon/polyaxon/libs/http.py", line 85, in safe_request
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 312, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 462, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 9, 11, 11, 57, 51, 77079, tzinfo=<UTC>) is not JSON serializable
"  
```

### To Reproduce

Add this entry to config file:

```
integrations:
  webhooks:
  - url: http://internalwebhook
    method: POST
```
and then try to send a experiment notification.
In my case `internalwebhook` is a custom service deployed within kubernetes, the pod runs a python module with flask to listen requests (webhook). Note that is not necessary provide this pod and service because of exception is raised before to send the request.

### Expected behavior

A valid request is sent from the polyaxon api pod (task dispatched successfully)

### Environment
kubernetes on google (GKE)

**Comment by mouradmourafiq** [comment]
Hi @engapa, can you mention the Polyaxon verison you are running as well.

**Comment by mouradmourafiq** [comment]
I was able to reproduce the issue, it's weird that the event goes through the same pipeline and does not raise for slack for instance and it raises for the webhook.

I will make a fix shortly, and I will include it in the next release.
