### ISSUE TITLE
Unable to run experiment: Method Not Allowed

### ISSUE THREAD

**Issue by salvadr** [polyaxon/polyaxon#203]
### Describe the bug
I'm testing polyaxon locally with minikube, everything is installed, set up and running. I've logged in successfully and have access to the dashboard. I've also created a project. But when trying to run an experiment I get a timeout error, and the logs display a "Method not allowed" error over endpoint `/api/v1/root/polyaxon-test/experiments/` (POST), (the endpoint works with GET method):

```
WARNING 2018-10-10 17:17:44,364 base 86 139633434826496 Method Not Allowed (POST): /api/v1/root/polyaxon-test/experiments/
WARNING 2018-10-10 17:17:44,374 log 86 139633434826496 Method Not Allowed: /api/v1/root/polyaxon-test/experiments/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 244, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/polyaxon/web/../polyaxon/api/experiments/views.py", line 182, in perform_create
    instance = serializer.save(user=self.request.user, project=project)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 940, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 758, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/polyaxon/web/../polyaxon/libs/decorators.py", line 90, in __call__
    return self.f(*args, **kwargs)
  File "/polyaxon/web/../polyaxon/libs/decorators.py", line 43, in __call__
    return self.f(*args, **kwargs)
  File "/polyaxon/web/../polyaxon/libs/decorators.py", line 20, in __call__
    return self.f(*args, **kwargs)
  File "/polyaxon/web/../polyaxon/signals/experiments.py", line 222, in start_new_experiment
    countdown=1)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/base.py", line 744, in send_task
    self.backend.on_task_call(P, task_id)
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/redis.py", line 265, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/redis.py", line 126, in consume_from
    self._consume_from(task_id)
  File "/usr/local/lib/python3.5/dist-packages/celery/backends/redis.py", line 132, in _consume_from
    self._pubsub.subscribe(key)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2482, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2404, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2408, in _execute
    return command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 486, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
Wed Oct 10 17:17:44 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /api/v1/root/polyaxon-test/experiments/ (ip 172.17.0.1) !!!
Wed Oct 10 17:17:44 2018 - uwsgi_response_write_headers_do(): Broken pipe [core/writer.c line 248] during POST /api/v1/root/polyaxon-test/experiments/ (172.17.0.1)
OSError: write error
```

### To Reproduce
`polyaxon run`

It occurs regardless of the config at polyaxonfile.yml

### Expected behavior
The experiment is run.

### Environment
- macOS High Sierra version 10.13.6 (17G65)
- Minikube

Kubernetes services:
```
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.96.0.1
Port:              https  443/TCP
TargetPort:        8443/TCP
Endpoints:         192.168.99.100:8443
Session Affinity:  ClientIP
Events:            <none>


Name:                     polyaxon
Namespace:                default
Labels:                   run=polyaxon
Annotations:              <none>
Selector:                 run=polyaxon
Type:                     NodePort
IP:                       10.99.19.173
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  32012/TCP
Endpoints:                172.17.0.2:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

Pods:
```
polyaxon-docker-registry-5bbd4b7fd4-m76cw      1/1       Running   0          6h
polyaxon-polyaxon-api-786747d4d9-mxscg         2/2       Running   0          6h
polyaxon-polyaxon-beat-b5f9f4cf9-mjk56         0/2       Pending   0          6h
polyaxon-polyaxon-events-7fd7986c9-bn5qk       0/1       Pending   0          6h
polyaxon-polyaxon-hpsearch-66d89764c4-6tgr5    0/1       Pending   0          6h
polyaxon-polyaxon-monitors-7f9497d5b5-8dt5h    0/2       Pending   0          6h
polyaxon-polyaxon-resources-djrj7              1/1       Running   0          6h
polyaxon-polyaxon-scheduler-8698cffc5d-6dh8h   0/1       Pending   0          6h
polyaxon-postgresql-78d4cff55c-87dmw           1/1       Running   0          6h
polyaxon-rabbitmq-6cd456989f-rsdsd             1/1       Running   0          6h
polyaxon-redis-599457cd67-h796l                0/1       Pending   0          6h
```

**Comment by mouradmourafiq** [comment]
It seems like some pods are still in the pending state, so I would not expect the cluster to run. Can you check why the redis pod is not running?

**Comment by bmiselis** [comment]
I'm also having issues with polyaxon-redis both master and slave being stuck on pending phase. How could I check why their pods are not running?

**Comment by mouradmourafiq** [comment]
you can disable the redis persistence:

```
redis:
  persistence:
    enabled: False
```

A similar [issue](https://github.com/polyaxon/polyaxon/issues/539#issuecomment-517348664) related to redis.

**Comment by bmiselis** [comment]
Okay, I'll give it a try. If I disable redis persistence, in practice how would that affect my cluster's behaviour?

**Comment by bmiselis** [comment]
Still getting:

```
kubectl describe pod polyaxon-redis-master-0 -n polyaxon
Name:           polyaxon-redis-master-0
Namespace:      polyaxon
Priority:       0
Node:           <none>
Labels:         app=redis
                chart=redis-7.0.0
                controller-revision-hash=polyaxon-redis-master-586b8cfcdb
                release=polyaxon
                role=master
                statefulset.kubernetes.io/pod-name=polyaxon-redis-master-0
Annotations:    checksum/configmap: 48e325cfd318a26e7f3e91c895f1708a886dcc349c5d1be97083cb78b458d049
                checksum/health: 8c94a3d20e853606f148706afb574faab19c5da8030408f3a6b5273346425ae9
                checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Status:         Pending
IP:
Controlled By:  StatefulSet/polyaxon-redis-master
Containers:
  polyaxon-redis:
    Image:      docker.io/bitnami/redis:5.0.4
    Port:       6379/TCP
    Host Port:  0/TCP
    Command:
      /bin/bash
      -c
      if [[ -n $REDIS_PASSWORD_FILE ]]; then
        password_aux=`cat ${REDIS_PASSWORD_FILE}`
        export REDIS_PASSWORD=$password_aux
      fi
      if [[ ! -f /opt/bitnami/redis/etc/master.conf ]];then
        cp /opt/bitnami/redis/mounted-etc/master.conf /opt/bitnami/redis/etc/master.conf
      fi
      if [[ ! -f /opt/bitnami/redis/etc/redis.conf ]];then
        cp /opt/bitnami/redis/mounted-etc/redis.conf /opt/bitnami/redis/etc/redis.conf
      fi
      ARGS=("--port" "${REDIS_PORT}")
      ARGS+=("--protected-mode" "no")
      ARGS+=("--include" "/opt/bitnami/redis/etc/redis.conf")
      ARGS+=("--include" "/opt/bitnami/redis/etc/master.conf")
      /run.sh ${ARGS[@]}

    Liveness:   exec [sh -c /health/ping_local.sh 5] delay=5s timeout=5s period=5s #success=1 #failure=5
    Readiness:  exec [sh -c /health/ping_local.sh 5] delay=5s timeout=1s period=5s #success=1 #failure=5
    Environment:
      REDIS_REPLICATION_MODE:  master
      ALLOW_EMPTY_PASSWORD:    yes
      REDIS_PORT:              6379
    Mounts:
      /data from redis-data (rw)
      /health from health (rw)
      /opt/bitnami/redis/etc/ from redis-tmp-conf (rw)
      /opt/bitnami/redis/mounted-etc from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zgf9p (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  redis-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  redis-data-polyaxon-redis-master-0
    ReadOnly:   false
  health:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      polyaxon-redis-health
    Optional:  false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      polyaxon-redis
    Optional:  false
  redis-tmp-conf:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-zgf9p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zgf9p
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  0s (x4 over 37s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
```

when using the following config:
```
ingress:
  enabled: false

rbac:
  enabled: false

redis:
  persistence:
    enabled: False

serviceType: NodePort
```

**Comment by mouradmourafiq** [comment]
It depends if redis is used as broker or not, but not a big impact. You can also set a default storage class or check the redis helm chart to customize the behaviour.
