### ISSUE TITLE
Starting of tensorboard for experiment group "failed"

### ISSUE THREAD

**Issue by naetherm** [polyaxon/polyaxon#239]
### Describe the bug
I receive the following stack trace when starting a tensorboard for an experiment/experiment group. The tensorboard will be created and is available, the problem is just the provided stack trace:
```
polyaxon tensorboard -g 100 start

Tensorboard is being deployed for group `100`

It may take some time before you can access tensorboard.

Your tensorboard will be available on:

Traceback (most recent call last):
  File "/xxx/polyaxon/cli/bin/polyaxon", line 11, in <module>
    sys.exit(cli())
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/polyaxon_cli/logger.py", line 54, in clean_outputs_wrapper
    raise e
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/polyaxon_cli/logger.py", line 48, in clean_outputs_wrapper
    return fn(*args, **kwargs)
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/polyaxon_cli/cli/tensorboard.py", line 238, in start
    clint.textui.puts(get_tensorboard_url(user, project_name, experiment, group))
  File "/xxx/polyaxon/cli/lib/python3.5/site-packages/polyaxon_cli/cli/tensorboard.py", line 27, in get_tensorboard_url
    PolyaxonClient().auth.http_host,
AttributeError: 'AuthApi' object has no attribute 'http_host'
```

### To Reproduce
Starting an experiment (group) and then starting a tensorboard.

### Expected behavior
Link to the tensorboard instance.

### Environment
Kubernetes: 1.12.2 (Ubuntu 18.04.1)

Local Machine: Ubuntu 16.04

#### polyaxon version
```
Current cli version: 0.2.9.

Supported cli versions:
--------------  -----
latest_version  0.2.9
min_version     0.2.3
--------------  -----
```

#### polyaxon version --platform
```
Current platform version: 0.2.9.

Supported platform versions:
--------------  -----
latest_version  0.2.9
min_version     0.2.7
--------------  -----
```

**Comment by mouradmourafiq** [comment]
Already fixed.

**Comment by naetherm** [comment]
Perfect. Thanks.
