### ISSUE TITLE
Using Azure mount  throws errors with polyaxon examples

### ISSUE THREAD

**Issue by posix4e** [polyaxon/polyaxon#302]
### Describe the bug
Azure mounts seem broke
```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from polyaxon_helper import get_data_paths, get_outputs_path
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_helper/__init__.py", line 20, in <module>
    experiment = Experiment()
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_client/tracking/experiment.py", line 45, in __init__
    outputs_store=outputs_store)
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_client/tracking/base.py", line 41, in __init__
    self.set_outputs_store(outputs_path=get_outputs_path(), set_env_vars=True)
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_client/tracking/base.py", line 47, in set_outputs_store
    self.outputs_store = outputs_store or StoreManager(path=outputs_path)
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_client/stores/stores/manager.py", line 18, in __init__
    store = BaseStore.get_store_for_path(path=path)
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_client/stores/stores/base_store.py", line 66, in get_store_for_path
    return cls.get_store_for_type(store_type=store_type, store_access=store_access)
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_client/stores/stores/base_store.py", line 72, in get_store_for_type
    return cls.get_store(store_type=store_type, **store_access)
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_client/stores/stores/base_store.py", line 36, in get_store
    from polyaxon_client.stores.stores.azure_store import AzureStore
  File "/usr/local/lib/python2.7/dist-packages/polyaxon_client/stores/stores/azure_store.py", line 9, in <module>
    from azure.common import AzureMissingResourceHttpError
ImportError: No module named azure.common
```
### To Reproduce
When using azure mounts on the polyaxon-example I get this error

### Expected behavior
No errors when accessing azure

**Comment by mouradmourafiq** [comment]
You probably should read this part of the [documentation](https://docs.polyaxon.com/customization/customize_outputs_and_data/#for-azure-storage). The client does not bundle the storage requirements.

Also the examples' code is not supposed to work out of the box when using the blob storage (other stores as well) since we currently rely on the clients to interact with the storage api. The behaviour you are expecting will be the default when #273 is finished.
