### ISSUE TITLE
polyaxon check fails if typo in polyaxonfile

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#356]
### Describe the bug

Uncomprehenisble error is raised if there is a typo in polyaxonfile.yaml.
For example, `polyaxonfile.yaml`:
```
---
version: 1

kind: group

environment:
  resources:
      gpu:
        requests: 1
        limits: 1

builds:
  image: nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

hptuning:
  concurrency: 2
  matrix:
    a:
      values: [256, 368, 512, 768]
    b: 
      values: [0.1, 0.2, 0.4, 0.5]

run:
  cmd:
    - echo "Check nvidia-smi"
    - export PATH=$PATH:/usr/local/nvidia/bin
    - nvidia-smi
```
There is a typo in `builds` instead of `build`. The output is the following:

```
$ polyaxon version
Current cli version: 0.3.8.
Supported cli versions:
--------------  -----
latest_version  0.3.0
min_version     0.3.8
--------------  -----

$ polyaxon check -f polyaxonfile.yaml 
Traceback (most recent call last):
  File "/home/user/.local/bin/polyaxon", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/polyaxon_cli/logger.py", line 54, in clean_outputs_wrapper
    raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2717' in position 0: ordinal not in range(128)
```

**Comment by mouradmourafiq** [comment]
What os are you using?

**Comment by mouradmourafiq** [comment]
Ok I see the error is on pyhton2.x

**Comment by vfdev-5** [comment]
Yes, python 2.7 on Ubuntu 16.04

**Comment by mouradmourafiq** [comment]
Should be part of the next release v0.3.9, Thanks for reporting this one.
