### ISSUE TITLE
Failed to fetch logs: Transport endpoint is not connected

### ISSUE THREAD

**Issue by spchuang** [polyaxon/polyaxon#380]
### Describe the bug

I trained a model and logs are displayed properly in the beginning. After the training (~2 days), I checked back again, and it has issue fetching the logs.

These are the error logs from the API server. 

```
[pid: 66247|app: 0|req: 9212/36807] 10.244.0.1 () {46 vars in 1161 bytes} [Mon Feb 25 01:48:01 2019] GET /api/v1/root/drone_maskrcnn/experiments/53/logs => generated 1341 bytes in 131 msecs (HTTP/1.1 500) 4 headers in 151 bytes (1 switches on core 0)
ERROR 2019-02-25 01:48:01,999 log 66249 140231795607360 Internal Server Error: /api/v1/root/drone_maskrcnn/experiments/53/logs
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/polyaxon/web/../polyaxon/api/endpoint/base.py", line 128, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/polyaxon/web/../polyaxon/api/endpoint/base.py", line 125, in dispatch
    response = handler(request, *args, **kwargs)
  File "/polyaxon/web/../polyaxon/api/experiments/views.py", line 635, in get
    wrapped_file = FileWrapper(open(log_path, 'rb'), chunk_size)
OSError: [Errno 107] Transport endpoint is not connected: '/logs/root/xxxx/experiments/53'
```
### To Reproduce

Not sure how to reproduce it since it's the first time it happened and nothing was done. 

### Expected behavior
See logs on dashboard. If disconnected, the server should reestablish the connections.

### Environment

**Comment by mouradmourafiq** [comment]
More info is needed, namely the environment, what version are you running, what type of persistence are you using for the logs?

In any case this [section](https://docs.polyaxon.com/configuration/custom-logs-storage/) could be useful. I also added a new [faq](https://docs.polyaxon.com/faq/i-cannot-fetch-logs/) to mention cases when this could happen.

**Comment by spchuang** [comment]
we resolved it by restarting the servers. I think our kubernetes cluster had some network issues then we started getting this error. Not sure how to reproduce tho.
