### ISSUE TITLE
Scheduler was CrashLoopBackOff on 0.4.2

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#403]
### Describe the bug
We tried to upgrade polyaxon from 0.4.1 to 0.4.2. However, the statuses of schedulers on k8s were `CrashLoopBackOff`. The schedulers didn't work as I expected. The error logs of scheduler pod are on the bottom.

### To Reproduce
```
helm upgrade polyaxon polyaxon/polyaxon -f polyaxon/polyaxon-config.yml --version 0.4.2 --namespace polyaxon
```

### Expected behavior
The schedulers shoudl work. 

### Environment
- Google Kubernetes Engine: v1.11.6-gke.11
- Existing Polyaxon: 0.4.1
- `data`, `outputs`, `logs`: Google Cloud Storage

## Error log of scheduler pod
```
Traceback (most recent call last):
  File "/polyaxon/polyaxon/stores/service.py", line 372, in _validate_persistence
    VolumeConfig.from_dict(persistence)
  File "/usr/local/lib/python3.6/dist-packages/polyaxon_schemas/base.py", line 117, in from_dict
    return cls.SCHEMA(unknown=unknown).load(value)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 706, in load
    postprocess=True,
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 866, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'secretKey': ['Unknown field.'], 'secret': ['Unknown field.'], 'store': ['Unknown field.'], 'bucket': ['Unknown field.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/polyaxon/polyaxon/stores/service.py", line 375, in _validate_persistence
    StoreConfig.from_dict(persistence)
  File "/usr/local/lib/python3.6/dist-packages/polyaxon_schemas/base.py", line 117, in from_dict
    return cls.SCHEMA(unknown=unknown).load(value)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 706, in load
    postprocess=True,
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 866, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'existingClaim': ['Unknown field.'], 'mountPath': ['Unknown field.'], 'hostPath': ['Unknown field.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/polyaxon/polyaxon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/polyaxon/polyaxon/stores/apps.py", line 11, in ready
    config.setup_stores_service()
  File "/polyaxon/polyaxon/polyaxon/config_manager.py", line 274, in setup_stores_service
    stores.validate()
  File "/usr/local/lib/python3.6/dist-packages/hestia/service_interface.py", line 70, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/polyaxon/polyaxon/stores/service.py", line 405, in validate
    self._validate_logs()
  File "/polyaxon/polyaxon/stores/service.py", line 386, in _validate_logs
    persistence_type='PERSISTENCE_LOGS')
  File "/polyaxon/polyaxon/stores/service.py", line 378, in _validate_persistence
    persistence_name, persistence_type
hestia.service_interface.InvalidService: Persistence `default`, of type `PERSISTENCE_LOGS`, is not valid.
Running...
ERROR 2019-03-14 23:57:14,960 signal 20 139780704196416 Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f2136e8a4a8>> raised: InvalidService('Persistence `default`, of type `PERSISTENCE_LOGS`, is not valid.',)
Traceback (most recent call last):
  File "/polyaxon/polyaxon/stores/service.py", line 372, in _validate_persistence
    VolumeConfig.from_dict(persistence)
  File "/usr/local/lib/python3.6/dist-packages/polyaxon_schemas/base.py", line 117, in from_dict
    return cls.SCHEMA(unknown=unknown).load(value)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 706, in load
    postprocess=True,
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 866, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'bucket': ['Unknown field.'], 'secretKey': ['Unknown field.'], 'secret': ['Unknown field.'], 'store': ['Unknown field.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/polyaxon/polyaxon/stores/service.py", line 375, in _validate_persistence
    StoreConfig.from_dict(persistence)
  File "/usr/local/lib/python3.6/dist-packages/polyaxon_schemas/base.py", line 117, in from_dict
    return cls.SCHEMA(unknown=unknown).load(value)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 706, in load
    postprocess=True,
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 866, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'hostPath': ['Unknown field.'], 'mountPath': ['Unknown field.'], 'existingClaim': ['Unknown field.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.6/dist-packages/celery/fixups/django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/local/lib/python3.6/dist-packages/celery/fixups/django.py", line 120, in validate_models
    self.django_setup()
  File "/usr/local/lib/python3.6/dist-packages/celery/fixups/django.py", line 116, in django_setup
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/polyaxon/polyaxon/stores/apps.py", line 11, in ready
    config.setup_stores_service()
  File "/polyaxon/polyaxon/polyaxon/config_manager.py", line 274, in setup_stores_service
    stores.validate()
  File "/usr/local/lib/python3.6/dist-packages/hestia/service_interface.py", line 70, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/polyaxon/polyaxon/stores/service.py", line 405, in validate
    self._validate_logs()
  File "/polyaxon/polyaxon/stores/service.py", line 386, in _validate_logs
    persistence_type='PERSISTENCE_LOGS')
  File "/polyaxon/polyaxon/stores/service.py", line 378, in _validate_persistence
    persistence_name, persistence_type
hestia.service_interface.InvalidService: Persistence `default`, of type `PERSISTENCE_LOGS`, is not valid.
Traceback (most recent call last):
  File "/polyaxon/polyaxon/stores/service.py", line 372, in _validate_persistence
    VolumeConfig.from_dict(persistence)
  File "/usr/local/lib/python3.6/dist-packages/polyaxon_schemas/base.py", line 117, in from_dict
    return cls.SCHEMA(unknown=unknown).load(value)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 706, in load
    postprocess=True,
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 866, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'bucket': ['Unknown field.'], 'secretKey': ['Unknown field.'], 'secret': ['Unknown field.'], 'store': ['Unknown field.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/polyaxon/polyaxon/stores/service.py", line 375, in _validate_persistence
    StoreConfig.from_dict(persistence)
  File "/usr/local/lib/python3.6/dist-packages/polyaxon_schemas/base.py", line 117, in from_dict
    return cls.SCHEMA(unknown=unknown).load(value)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 706, in load
    postprocess=True,
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 866, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'hostPath': ['Unknown field.'], 'mountPath': ['Unknown field.'], 'existingClaim': ['Unknown field.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.6/dist-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.6/dist-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/usr/local/lib/python3.6/dist-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.6/dist-packages/celery/fixups/django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/local/lib/python3.6/dist-packages/celery/fixups/django.py", line 120, in validate_models
    self.django_setup()
  File "/usr/local/lib/python3.6/dist-packages/celery/fixups/django.py", line 116, in django_setup
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/polyaxon/polyaxon/stores/apps.py", line 11, in ready
    config.setup_stores_service()
  File "/polyaxon/polyaxon/polyaxon/config_manager.py", line 274, in setup_stores_service
    stores.validate()
  File "/usr/local/lib/python3.6/dist-packages/hestia/service_interface.py", line 70, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/polyaxon/polyaxon/stores/service.py", line 405, in validate
    self._validate_logs()
  File "/polyaxon/polyaxon/stores/service.py", line 386, in _validate_logs
    persistence_type='PERSISTENCE_LOGS')
  File "/polyaxon/polyaxon/stores/service.py", line 378, in _validate_persistence
    persistence_name, persistence_type
hestia.service_interface.InvalidService: Persistence `default`, of type `PERSISTENCE_LOGS`, is not valid.
```

**Comment by mouradmourafiq** [comment]
Sorry for that, I patched the release, please rerun upgrade it should go through.
Let me know.

**Comment by yu-iskw** [comment]
Thanks. I will give it a try.
