### ISSUE TITLE
polyaxon-example tensorflow mnist data download failed on microk8s

### ISSUE THREAD

**Issue by VinayTeki** [polyaxon/polyaxon#405]
I've deployed polyaxon on my local machine using microk8s which supports gpu usage with no hassle.
Problem:
Deployment Configuration:

```YAML
serviceType: NodePort
persistence:
  logs:
    existingClaim:
    mountPath: "/polyaxon-logs"
    hostPath: "/tmp/polyaxon/logs"
  repos:
    existingClaim:
    mountPath: "/polyaxon-repos"
    hostPath: "/tmp/polyaxon/repos"
  upload:
    existingClaim:
    mountPath: "/tmp/upload"
    hostPath: "/tmp/polyaxon/upload"
  data:
    data1:
      mountPath: "/data/1"
      hostPath: "/tmp/polyaxon/data"
      readOnly: false
  outputs:
    outputs1:
      mountPath: "/outputs/1"
      hostPath: "/tmp/polyaxon/outputs"
      readOnly: false
```

Now when I run the polyaxon-example of polyaxon-quick-start repo with the yaml file 
```yaml
---
version: 1

kind: experiment

build:
  image: tensorflow/tensorflow:1.4.1-py3
  build_steps:
    - pip3 install --no-cache-dir -U polyaxon-client==0.4.2

run:
cmd: python3 -u model.py  # Use default params
```

Urllib module throws an error during download of mnist data in the below line of model.py script
 `mnist = input_data.read_data_sets(data_paths, one_hot=False)`

Error from urllib:
```
2019-03-21 07:49:16 UTC -- /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

2019-03-21 07:49:16 UTC -- /usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
2019-03-21 07:49:16 UTC -- from ._conv import register_converters as _register_converters
2019-03-21 07:49:17 UTC -- {'data1': '/data/1'}
2019-03-21 07:49:27 UTC -- Traceback (most recent call last):
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
2019-03-21 07:49:27 UTC -- h.request(req.get_method(), req.selector, req.data, headers)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/http/client.py", line 1106, in request
2019-03-21 07:49:27 UTC -- self._send_request(method, url, body, headers)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
2019-03-21 07:49:27 UTC -- self.endheaders(body)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
2019-03-21 07:49:27 UTC -- self._send_output(message_body)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
2019-03-21 07:49:27 UTC -- self.send(msg)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/http/client.py", line 877, in send
2019-03-21 07:49:27 UTC -- self.connect()
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/http/client.py", line 1252, in connect
2019-03-21 07:49:27 UTC -- super().connect()
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/http/client.py", line 849, in connect
2019-03-21 07:49:27 UTC -- (self.host,self.port), self.timeout, self.source_address)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/socket.py", line 693, in create_connection
2019-03-21 07:49:27 UTC -- for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
2019-03-21 07:49:27 UTC -- for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2019-03-21 07:49:27 UTC -- socket.gaierror: [Errno -3] Temporary failure in name resolution
2019-03-21 07:49:27 UTC --

2019-03-21 07:49:27 UTC -- During handling of the above exception, another exception occurred:
2019-03-21 07:49:27 UTC --
2019-03-21 07:49:27 UTC -- Traceback (most recent call last):
2019-03-21 07:49:27 UTC -- File "model.py", line 28, in <module>
2019-03-21 07:49:27 UTC -- mnist = input_data.read_data_sets(data_paths, one_hot=False)
2019-03-21 07:49:27 UTC -- File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 240, in read_data_sets
2019-03-21 07:49:27 UTC -- source_url + TRAIN_IMAGES)
2019-03-21 07:49:27 UTC -- File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 208, in maybe_download
2019-03-21 07:49:27 UTC -- temp_file_name, _ = urlretrieve_with_retry(source_url)
2019-03-21 07:49:27 UTC -- File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 165, in wrapped_fn
2019-03-21 07:49:27 UTC -- return fn(*args, **kwargs)
2019-03-21 07:49:27 UTC -- File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 190, in urlretrieve_with_retry
2019-03-21 07:49:27 UTC -- return urllib.request.urlretrieve(url, filename)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
2019-03-21 07:49:27 UTC -- with contextlib.closing(urlopen(url, data)) as fp:
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
2019-03-21 07:49:27 UTC -- return opener.open(url, data, timeout)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/urllib/request.py", line 466, in open
2019-03-21 07:49:27 UTC -- response = self._open(req, data)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
2019-03-21 07:49:27 UTC -- '_open', req)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
2019-03-21 07:49:27 UTC -- result = func(*args)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
2019-03-21 07:49:27 UTC -- context=self._context, check_hostname=self._check_hostname)
2019-03-21 07:49:27 UTC -- File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
2019-03-21 07:49:27 UTC -- raise URLError(err)
2019-03-21 07:49:27 UTC -- urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

Would be of great help if anyone can point me out in the right direction.

**Comment by VinayTeki** [comment]
The issue is with the pods not being able to access internet through available network interfaces.
This is solved by configuring firewall with iptables
```
sudo iptables -P FORWARD ACCEPT
```
