### ISSUE TITLE
polyaxon init fails with UnicodeEncodeError

### ISSUE THREAD

**Issue by flackbash** [polyaxon/polyaxon#410]
### Describe the bug
When trying to init a project, e.g. the quick-start project following the [docs](https://docs.polyaxon.com/concepts/quick-start-internal-repo/), I get an UnicodeEncodeError.
May be related to #356.
### To Reproduce
```
$ polyaxon init quick-start
Traceback (most recent call last):
  File "/home/user/.local/bin/polyaxon", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/polyaxon_cli/logger.py", line 56, in clean_outputs_wrapper
    raise e
  File "/home/user/.local/lib/python3.6/site-packages/polyaxon_cli/logger.py", line 50, in clean_outputs_wrapper
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/polyaxon_cli/cli/init.py", line 80, in init
    Printer.print_success('Project was initialized', add_sign=True)
  File "/home/user/.local/lib/python3.6/site-packages/polyaxon_cli/utils/formatting.py", line 73, in print_success
    click.secho(u'\n{}{}\n'.format(u'\u2713 ' if add_sign else '', text), fg='green')
  File "/home/user/.local/lib/python3.6/site-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/home/user/.local/lib/python3.6/site-packages/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 6: ordinal not in range(256)
```
### Environment
I'm using polyaxon-cli version 0.4.2 on a machine running Ubuntu 18.04.1 LTS.

**Comment by j-kohn** [comment]
Hi, can check your requirements just to make sure: `pip freeze | grep polyaxon`?

**Comment by flackbash** [comment]
Sure:
```
$ pip3 freeze | grep polyaxon
polyaxon-cli==0.4.2
polyaxon-client==0.4.2
polyaxon-deploy==0.4.2
polyaxon-schemas==0.4.2
```

**Comment by mouradmourafiq** [comment]
@j-kohn I think it's best if we drop those unicode signs altogether, this would just make the tool more robust when dealing with encoding issues. Let me know if you can do that, otherwise I can revert that change since I introduced it.

@flackbash thanks for your quick reply, we will update the issue once it's solved.

**Comment by mouradmourafiq** [comment]
I just pushed a fix, can you try installing the cli using `pip install -e git+https://github.com/polyaxon/polyaxon-cli.git@master#egg=polyaxon-cli==0.4.2`

**Comment by flackbash** [comment]
This seems to fix it, I'm not getting the error anymore. Thank you!
