### ISSUE TITLE
Validating config.yml leads to errors

### ISSUE THREAD

**Issue by mallochio** [polyaxon/polyaxon#443]
When I try to validate config.yml for polyaxon using the command below stated in the docs, I get the following TypeError stating that the environment can only have strings.
`>polyaxon deploy -f config.yml --check`

> Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\polyaxon.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\polyaxon_cli\logger.py", line 56, in clean_outputs_wrapper
    raise e
  File "c:\program files\python36\lib\site-packages\polyaxon_cli\logger.py", line 50, in clean_outputs_wrapper
    return fn(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\polyaxon_cli\cli\deploy.py", line 53, in deploy
    manager.check()
  File "c:\program files\python36\lib\site-packages\polyaxon_cli\managers\deploy.py", line 103, in check
    check = self.check_for_kubernetes()
  File "c:\program files\python36\lib\site-packages\polyaxon_cli\managers\deploy.py", line 59, in check_for_kubernetes
    command_exist = self.kubectl.execute(args=[], is_json=False)
  File "c:\program files\python36\lib\site-packages\polyaxon_deploy\operators\kubectl.py", line 33, in execute
    return self._execute(params=params, env=self.env(), is_json=is_json)
  File "c:\program files\python36\lib\site-packages\polyaxon_deploy\operators\cmd_operator.py", line 17, in _execute
    ps = subprocess.Popen(params, env=env, stdout=stdout, stderr=stderr)
  File "c:\program files\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\program files\python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
TypeError: environment can only contain strings

I'm trying to run polyaxon on minikube installed on a windows 10 system.
Thanks in advance.

**Comment by mouradmourafiq** [comment]
Can you share your config

**Comment by mallochio** [comment]
Thanks for the response!
My config file looks exactly like the instructions say it should be:
`deploymentType: minikube

rbac:
  enabled: false

ingress:
  enabled: false

serviceType: NodePort`

I also tried with the rbac enabled and starting minikube with the `--extra-config=apiserver.authorization-mode=RBAC` flag, but the error still persists.

I also cannot seem to be able to view the polyaxon CLI version. When I run the command `polyaxon version` STDOUT shows the following error.

>Could not get cli version.
Error message `Error connecting to Polyaxon server on `http://localhost:8090/api/v1/versions/cli/`.
An Error `HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/versions/cli/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000148EA00D208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))` occurred.
Check your host and ports configuration and your internet connection.`.

**Comment by mouradmourafiq** [comment]
it seems like the cli is not working, can you `pip freeze | grep polyaxon`?

**Comment by mallochio** [comment]
This is what is got as a result of your command.

> polyaxon-cli==0.4.4
> polyaxon-client==0.4.4
> polyaxon-deploy==0.4.4
> polyaxon-schemas==0.4.4

**Comment by mouradmourafiq** [comment]
Ok I see, you can skip this step, and use helm to deploy Polyaxon. The docs mention that you can use the cli or the helm command to deploy.

**Comment by mallochio** [comment]
I deleted and reinstalled minikube and used helm to deploy polyaxon like you mentioned. That actually worked and I ended up being able to see polyaxon with a deployed status on helm. Thanks!

**Comment by mallochio** [comment]
Apologies for reopening the issue. Although the polyaxon version shows up as deployed on helm, I am now unable to use the CLI for most functions due to a connection error to the polyaxon server. 

For example, when I do `polyaxon version` or `polyaxon whoami`, I see this error.

> Could not get cli version.
Error message `Error connecting to Polyaxon server on `http://localhost:8090/api/v1/versions/cli/`.
An Error `HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v1/versions/cli/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D313B365F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))` occurred.
Check your host and ports configuration and your internet connection.`

Reopening the same issue, because the error was repeated even before deployment succeeded with helm. Thanks in advance for your help.

**Comment by mouradmourafiq** [comment]
Can you access the polyaxon dashboard when you port forward the Polyaxon's nodeports using kubectl?

**Comment by mallochio** [comment]
Hi Mourad,

I deleted my minikube and did a reinstall from the beginning, and now the CLI seems to be working as expected. I can access the dashboard by using the CLI. Thanks for the help. Closing the issue now.
