### ISSUE TITLE
Problem with config file (image/dockerizer)

### ISSUE THREAD

**Issue by Waasil** [polyaxon/polyaxon#471]
### Describe the bug

Hello. After installing the polyaxon, I checked to see if it works properly. I have cloned that example (https://github.com/polyaxon/polyaxon-examples) and based on Quick-Start in documentation I have tried to run experiment with config file polyaxonfile.yml ("polyaxon run -f polyaxonfile.yml -u").
After a few minutes there was status 'failed'. I opened Config and I saw that image line is red.

![image](https://user-images.githubusercontent.com/20801127/58726368-d96a1880-83e1-11e9-96b8-8a74e3d77320.png)

I also checked Build Logs and there was following error:

### To Reproduce

```
2019-05-22 15:10:33 UTC -- E
2019-05-22 15:10:33 UTC -- R
2019-05-22 15:10:33 UTC -- R
2019-05-22 15:10:33 UTC -- O
2019-05-22 15:10:33 UTC -- R
2019-05-22 15:10:33 UTC -- :
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- C
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- u
2019-05-22 15:10:33 UTC -- l
2019-05-22 15:10:33 UTC -- d
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- n
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- t
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- b
2019-05-22 15:10:33 UTC -- u
2019-05-22 15:10:33 UTC -- i
2019-05-22 15:10:33 UTC -- l
2019-05-22 15:10:33 UTC -- d
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- t
2019-05-22 15:10:33 UTC -- h
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- i
2019-05-22 15:10:33 UTC -- m
2019-05-22 15:10:33 UTC -- a
2019-05-22 15:10:33 UTC -- g
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- ,
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- n
2019-05-22 15:10:33 UTC -- c
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- u
2019-05-22 15:10:33 UTC -- n
2019-05-22 15:10:33 UTC -- t
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- d
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- 5
2019-05-22 15:10:33 UTC -- 0
2019-05-22 15:10:33 UTC -- 0
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- S
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- v
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- E
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- :
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- I
2019-05-22 15:10:33 UTC -- n
2019-05-22 15:10:33 UTC -- t
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- n
2019-05-22 15:10:33 UTC -- a
2019-05-22 15:10:33 UTC -- l
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- S
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- v
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- E
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- (
2019-05-22 15:10:33 UTC -- "
2019-05-22 15:10:33 UTC -- C
2019-05-22 15:10:33 UTC -- a
2019-05-22 15:10:33 UTC -- n
2019-05-22 15:10:33 UTC -- n
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- t
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- l
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- c
2019-05-22 15:10:33 UTC -- a
2019-05-22 15:10:33 UTC -- t
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- s
2019-05-22 15:10:33 UTC -- p
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- c
2019-05-22 15:10:33 UTC -- i
2019-05-22 15:10:33 UTC -- f
2019-05-22 15:10:33 UTC -- i
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- d
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- D
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- c
2019-05-22 15:10:33 UTC -- k
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- f
2019-05-22 15:10:33 UTC -- i
2019-05-22 15:10:33 UTC -- l
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- :
2019-05-22 15:10:33 UTC --
2019-05-22 15:10:33 UTC -- D
2019-05-22 15:10:33 UTC -- o
2019-05-22 15:10:33 UTC -- c
2019-05-22 15:10:33 UTC -- k
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- r
2019-05-22 15:10:33 UTC -- f
2019-05-22 15:10:33 UTC -- i
2019-05-22 15:10:33 UTC -- l
2019-05-22 15:10:33 UTC -- e
2019-05-22 15:10:33 UTC -- "
2019-05-22 15:10:33 UTC -- )
2019-05-22 15:10:33 UTC -- Traceback (most recent call last):
2019-05-22 15:10:33 UTC -- File "dockerizer/build_cmd.py", line 37, in <module>
2019-05-22 15:10:33 UTC -- nocache=nocache)
2019-05-22 15:10:33 UTC -- File "/polyaxon/polyaxon/dockerizer/dockerizer/builders/native.py", line 160, in build
2019-05-22 15:10:33 UTC -- raise BuildException('The docker image could not be built.')
2019-05-22 15:10:33 UTC -- builders.exceptions.BuildException: The docker image could not be built.
```

### Expected behavior

Experiment should run. To run experiment I used line: "polyaxon run -f polyaxonfile.yml -u"

### Environment
Polyaxon 0.4.4
Ubuntu 18.04 LTS
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Do you have any idea what's wrong?

**Comment by mouradmourafiq** [comment]
The polyaxonfile you linked uses kaniko as a backend, and the logs are for the native builder, so something is wrong with the way you started the experiment.

Please feel free to reopen this issue if you still have the same problem.
