### ISSUE TITLE
Distributed training on 1-worker,1-ps and 1 master using (2 gpus, 1 cpu for the PS)

### ISSUE THREAD

**Issue by gurushantj** [polyaxon/polyaxon#475]
I am not able to do distributed training using 2 gpus (1 for worker,1 for  master) and 1 ps (using cpu).
Please refer the following polyaxon config file:

---
version: 1
kind: experiment
framework: tensorflow
tags: [examples]
environment:
  resources:
    gpu:
      requests: 1
      limits: 1
  replicas:
    n_workers: 1
    n_ps: 1
    default_worker:
      resources:
        gpu:
          requests: 1
          limits: 1
    default_ps:
      resources:
        cpu:
          requests: 1
          limits: 1
build:
  image: tensorflow/tensorflow:1.4.1-gpu
  build_steps:
    - pip install --no-cache-dir -U polyaxon-client==0.4.4
run:
  cmd:  python -u run.py --train-steps=400 --sync
#################end of config file #################
Example used to run: https://github.com/polyaxon/polyaxon-examples/tree/master/in_cluster/tensorflow/cifar10

Command to submit the polyaxon experiment : polyaxon run -f polyaxonfile_distributed.yml
------------------------------------------------------------------------------------------------------
Following is the error log from polyaxon console:
2019-06-17 10:36:56 UTC ps.0 -- /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2019-06-17 10:36:57 UTC ps.0 -- Traceback (most recent call last):
2019-06-17 10:36:57 UTC ps.0 -- File "run.py", line 4, in <module>
2019-06-17 10:36:57 UTC ps.0 -- from cifar10_main import train
2019-06-17 10:36:57 UTC ps.0 -- File "/code/cifar10_main.py", line 35, in <module>
2019-06-17 10:36:57 UTC ps.0 -- import cifar10
2019-06-17 10:36:57 UTC ps.0 -- File "/code/cifar10.py", line 21, in <module>
2019-06-17 10:36:57 UTC ps.0 -- import tensorflow as tf
2019-06-17 10:36:57 UTC ps.0 -- File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
2019-06-17 10:36:57 UTC ps.0 -- from tensorflow.python import *
2019-06-17 10:36:57 UTC ps.0 -- File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
2019-06-17 10:36:57 UTC ps.0 -- from tensorflow.python import pywrap_tensorflow
2019-06-17 10:36:57 UTC ps.0 -- File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
2019-06-17 10:36:57 UTC ps.0 -- raise ImportError(msg)
2019-06-17 10:36:57 UTC ps.0 -- ImportError: Traceback (most recent call last):
2019-06-17 10:36:57 UTC ps.0 -- File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
2019-06-17 10:36:57 UTC ps.0 -- from tensorflow.python.pywrap_tensorflow_internal import *
2019-06-17 10:36:57 UTC ps.0 -- File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
2019-06-17 10:36:57 UTC ps.0 -- _pywrap_tensorflow_internal = swig_import_helper()
2019-06-17 10:36:57 UTC ps.0 -- File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
2019-06-17 10:36:57 UTC ps.0 -- _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
2019-06-17 10:36:57 UTC ps.0 -- ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
2019-06-17 10:36:57 UTC ps.0 --
2019-06-17 10:36:57 UTC ps.0 --
2019-06-17 10:36:57 UTC ps.0 -- Failed to load the native TensorFlow runtime.
2019-06-17 10:36:57 UTC ps.0 --
2019-06-17 10:36:57 UTC ps.0 -- See https://www.tensorflow.org/install/install_sources#common_installation_problems
2019-06-17 10:36:57 UTC ps.0 --
2019-06-17 10:36:57 UTC ps.0 -- for some common reasons and solutions. Include the entire stack trace
2019-06-17 10:36:57 UTC ps.0 -- above this error message when asking for help.

**Comment by mouradmourafiq** [comment]
Closed as well in #690 , Polyaxon uses now by default TFJob for distributed jobs.
