### ISSUE TITLE
Docu: Dead link (unclear how to expose outputs to cloud storage)

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#480]
### Unclear documentation

I had problems to find information on how to expose outputs to some cloud storage (Docu on how to set up the connection to the cloud storage was very clear though!)
At some point I found the following (but I can't find it anymore...)
``` python
from polyaxon_client.tracking import Experiment
experiment = Experiment()
experiment.log_artifact("/path/to/some_output.file")
```
but this gave me the following traceback:
```
2019-06-19 08:02:00 UTC -- Traceback (most recent call last):
2019-06-19 08:02:00 UTC -- File "expose_output_test.py", line 5, in <module>
2019-06-19 08:02:00 UTC -- experiment.log_artifact("/path/to/some_output.file")
2019-06-19 08:02:00 UTC -- File "/usr/local/lib/python3.6/dist-packages/polyaxon_client/tracking/no_op.py", line 27, in wrapper
2019-06-19 08:02:00 UTC -- return f(*args, **kwargs)
2019-06-19 08:02:00 UTC -- File "/usr/local/lib/python3.6/dist-packages/polyaxon_client/tracking/experiment.py", line 283, in log_artifact
2019-06-19 08:02:00 UTC -- self.experiment.outputs_store.upload_file(file_path)
2019-06-19 08:02:00 UTC -- AttributeError: 'NoneType' object has no attribute 'outputs_store'
```
I concluded that `experiment.experiment` is `None`, so I added 
```python
experiment.experiment = experiment
```
 to my code. This worked, but I have a feeling that I'm not using the api as you intended :)

### Missing Documentation

https://docs.polyaxon.com/references/polyaxon-tracking-api/in-cluster-experiments/#artifacts
contains a dead link to
https://docs.polyaxon.com/references/polyaxon-tracking-api/experiments/log_artifact/

**Comment by mouradmourafiq** [comment]
That's a bug, I will change the docs until the bug is fixed in the next release.

**Comment by mouradmourafiq** [comment]
I just updated the docs to refer to `log_output`/`log_outputs`, these 2 methods will stay on the tracking api as deprected, normally `log_artifact`/`log_artifcats` will be the command to use starting from v0.5.
