### ISSUE TITLE
GCS does not work with quick-start example

### ISSUE THREAD

**Issue by codebreach** [polyaxon/polyaxon#483]
### Describe the bug
We have set up the cluster with 
```

persistence:
  outputs:
    outputs-gcs:
      store: gcs
      bucket: gs://REDACTED-polyaxon-output
      secret: gcs-credentials
      secretKey: key.json
  data:
    data-gcs:
      store: gcs
      bucket: gs://REDACTED-polyaxon-data
      secret: gcs-credentials
      secretKey: key.json
```

However when running the sample `quick-start` it fails with following logs. Please note that the key given in the config is not being used thus the tf code is trying to hit `metadata` server.

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

2019-06-24 07:47:39 UTC -- /usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

2019-06-24 07:47:39 UTC -- from ._conv import register_converters as _register_converters

2019-06-24 07:47:40 UTC -- 2019-06-24 07:47:40.386504: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 1.21688 seconds (attempt 1 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')
---snip---
2019-06-24 07:49:52 UTC -- 2019-06-24 07:49:52.038651: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 32.7288 seconds (attempt 10 out of 10), caused by: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')

2019-06-24 07:50:24 UTC -- 2019-06-24 07:50:24.786199: W tensorflow/core/platform/cloud/google_auth_provider.cc:160] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Aborted: All 10 retry attempts failed. The last failure: Unavailable: Error executing an HTTP request (HTTP response code 0, error code 6, error message 'Couldn't resolve host 'metadata'')".

2019-06-24 07:50:25 UTC -- Traceback (most recent call last):

2019-06-24 07:50:25 UTC -- File "model.py", line 26, in <module>

2019-06-24 07:50:25 UTC -- mnist = input_data.read_data_sets(data_paths, one_hot=False)

2019-06-24 07:50:25 UTC -- File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 240, in read_data_sets

2019-06-24 07:50:25 UTC -- source_url + TRAIN_IMAGES)

2019-06-24 07:50:25 UTC -- File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 204, in maybe_download

2019-06-24 07:50:25 UTC -- if not gfile.Exists(work_directory):

2019-06-24 07:50:25 UTC -- File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 253, in file_exists

2019-06-24 07:50:25 UTC -- pywrap_tensorflow.FileExists(compat.as_bytes(filename), status)

2019-06-24 07:50:25 UTC -- File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__

2019-06-24 07:50:25 UTC -- c_api.TF_GetCode(self.status.status))

2019-06-24 07:50:25 UTC -- tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request (HTTP response code 401, error code 0, error message '')

2019-06-24 07:50:25 UTC -- when reading metadata of gs://REDACTED-polyaxon-data//mnist
```

A quick search for GOOGLE_APPLICATION_CREDENTIALS reveals that it is only set in `tensorboard_spawner.` I would assume we would need to do this for all the spawners for GCS to work correctly?

### Expected behavior
It should work

### Environment
Polyaxon 0.4.4
Kuberentes/Helm

**Comment by mouradmourafiq** [comment]
The quick-start example is not supposed to work with GCS, it has code that manipulate paths manually.
When using GCS, or other cloud storages, Polyaxon only schedules the secrets to access to that cloud storage for all jobs/experiments, the user still has to use the secrets to authenticate and load/upload data, this way the platform stays agnostic to the underlaying language used, if you are using python you can use `polystores` for interacting with cloud storages.

Tensorboard only deals with outputs, and the platform how to schedule tensorbaord jobs and load correct secrets to consume the artifacts.

Please see [this](https://docs.polyaxon.com/integrations/data-on-gcs/#access-to-data-in-your-experimentsjobs) for data on GCS, and [this](https://docs.polyaxon.com/integrations/outputs-on-gcs/#storing-outputs-and-artifacts-in-your-experimentsjobs) for outputs on GCS.

**Comment by codebreach** [comment]
Thanks for the prompt reply.

We have a lot of models which are built on Tensorflow (which as your documentation points out, supports GCS out of the box). This internally uses `GOOGLE_APPLICATION_CREDENTIALS`. However looking at the documentation and the code I am unable to figure out how to get access to the key.json file in such a way that we can set this environment variable. This will allow us to use the existing code without changes. Longer term we will definitely move to using `polystores` but this will make the transition much better.

The documentation at https://docs.polyaxon.com/integrations/outputs-on-gcs/ says:
> If you are using Tensorflow, you won't need to do any further configuration since Tensorflow can natively use GCS, Polyaxon will automatically set the required environment variables so that Tensorflow can use the bucket.

**Comment by mouradmourafiq** [comment]
I see, if the store type is GCS, by making an instance of `Experiment`, it will set an outputs store that can communicate with GCS for storing tensorflow artifcats/models/checkpoints, however fro reading data it's not possible because a user might want to access to 2 buckets or more at the same time, and this is too complicated to handle out of the box.

So summarize, if your outputs store is GCS, creating an experiment instance will let your tensorflow code to store outputs without any further configuration.
