### ISSUE TITLE
`Job.log_output` doesn't work at polyaxon 0.5.1

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#502]
### Describe the bug
I tried to call `Job.log_output` to store a resulting file to GCS. But, I got the error. 

```
Traceback (most recent call last):

File "src/data.py", line 70, in <module>

job.log_output(tmp_file)

File "/usr/local/lib/python3.6/site-packages/polyaxon_client/tracking/no_op.py", line 27, in wrapper

return f(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/polyaxon_client/tracking/base.py", line 171, in log_output

self.log_artifact(filename)

File "/usr/local/lib/python3.6/site-packages/polyaxon_client/tracking/no_op.py", line 27, in wrapper

return f(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/polyaxon_client/tracking/job.py", line 231, in log_artifact

self.job.outputs_store.upload_file(file_path)

AttributeError: 'NoneType' object has no attribute 'outputs_store'
```

### To Reproduce
```
job = Job()
job.log_output(path_to_file)
```

### Expected behavior
I should upload the file to GCS.

### Environment
- Polyaxon: 0.5.1

**Comment by shotarok** [comment]
I'll put my mitigation here.

```
# These code don't work
job. log_output(tmp_file)
job.job.outputs_store.upload_file(tmp_file)

# This code works
job.outputs_store.upload_file(tmp_file)
```

**Comment by mouradmourafiq** [comment]
@yu-iskw I was going to look at it after finishing some work, but thanks to @shotarok the bug was due to a bad inheritance that was supposed to be fixed in earlier release.

**Comment by yu-iskw** [comment]
Thank you for fixing it quickly.

**Comment by mouradmourafiq** [comment]
Update: 0.5.2 with the hot fix is released.
