### ISSUE TITLE
polyaxon cli to get gpu node info raise ValidationError

### ISSUE THREAD

**Issue by QipengZhou** [polyaxon/polyaxon#533]
### Describe the bug
When I run `polyaxon cluster -n 1` raise the follow error
```shell
Traceback (most recent call last):
  File "/opt/polyaxon_cli/bin/polyaxon", line 11, in <module>
    sys.exit(cli())
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_cli/logger.py", line 56, in clean_outputs_wrapper
    raise e
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_cli/logger.py", line 50, in clean_outputs_wrapper
    return fn(*args, **kwargs)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_cli/cli/cluster.py", line 56, in cluster
    node_config = cluster_client.get_node(node)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_client/api/cluster.py", line 29, in get_node
    return self.prepare_results(response_json=response.json(), config=ClusterNodeConfig)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_client/api/base.py", line 69, in prepare_results
    if self.config.schema_response else response_json)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_schemas/base.py", line 117, in from_dict
    return cls.SCHEMA(unknown=unknown).load(value)  # pylint: disable=not-callable
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/marshmallow/schema.py", line 706, in load
    postprocess=True,
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/marshmallow/schema.py", line 866, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'gpus': {0: {'created_at': ['Unknown field.'], 'updated_at': ['Unknown field.']}, 1: {'created_at': ['Unknown field.'], 'updated_at': ['Unknown field.']}, 2: {'created_at': ['Unknown field.'], 'updated_at': ['Unknown field.']}, 3: {'created_at': ['Unknown field.'], 'updated_at': ['Unknown field.']}, 4: {'created_at': ['Unknown field.'], 'updated_at': ['Unknown field.']}, 5: {'created_at': ['Unknown field.'], 'updated_at': ['Unknown field.']}, 6: {'created_at': ['Unknown field.'], 'updated_at': ['Unknown field.']}, 7: {'created_at': ['Unknown field.'], 'updated_at': ['Unknown field.']}}}
```
Change [GPUSerializer](https://github.com/polyaxon/polyaxon/blob/master/polyaxon/api/nodes/serializers.py) to exclude fields: `created_at` and `updated_at` may fix this error.

**Comment by mouradmourafiq** [comment]
Can you run `polyaxon -v cluster -n 1`?

**Comment by QipengZhou** [comment]
I run `polyaxon -v cluster -n 1` return the following message:
```bash
Setting OrderedDict([('check_count', 2), ('current_version', '0.4.4'), ('min_version', '0.4.2'), ('log_handler', OrderedDict([('dsn', 'aHR0cHM6Ly84MTc4MjEwYjY4NDU0OGE1Yjk2YjgxMzFmYTY0NWM5ZTozY2IwZGI1OTY5NDU0NjNkYTUzMmUzNmRiZTQ4NjFmNUBzZW50cnkuaW8vMTE5NzQxNg=='), ('environment', 'production'), ('tags', {'cli_min_version': '0.4.2', 'cli_latest_version': '0.4.4', 'platform_min_version': '0.4.2', 'platform_latest_version': '0.4.4', 'chart_version': '0.4.4'})]))]) in the file .polyaxoncli
Starting request to url: http://192.168.1.160:30268/api/v1/nodes/1/ with params: None, data: None
Starting new HTTP connection (1): 192.168.1.160:30268
http://192.168.1.160:30268 "GET /api/v1/nodes/1/ HTTP/1.1" 200 None
Response Content: b'{"uuid":"63a0e26f2a0b40fe8cc9d6f5d635fa29","gpus":[{"uuid":"bb498e0702c34f43aff6f453b1fe2bd8","cluster_node":"63a0e26f2a0b40fe8cc9d6f5d635fa29","created_at":"2019-07-25T10:37:31.329759+02:00","updated_at":"2019-07-29T03:18:18.027076+02:00","index":0,"serial":"xxx","name":"xxx","memory":xxx},{"uuid":"7f5e8579e4794218b7319ef64a9d81a0","cluster_node":"63a0e26f2a0b40fe8cc9d6f5d635fa29","created_at":"2019-07-25T10:37:31.434526+02:00","updated_at":"2019-07-29T03:18:18.035297+02:00","index":1,"serial":"xxx","name":"xxx","memory":xxx},{"uuid":"e22957568f0d4fa9b77f8383d5bd9c60","cluster_node":"63a0e26f2a0b40fe8cc9d6f5d635fa29","created_at":"2019-07-25T10:37:31.451488+02:00","updated_at":"2019-07-29T03:18:18.043090+02:00","index":2,"serial":"xxx","name":"xxx","memory":xxx},{"uuid":"6670cd7737764918876ef0cc65c039d2","cluster_node":"63a0e26f2a0b40fe8cc9d6f5d635fa29","created_at":"2019-07-25T10:37:31.467310+02:00","updated_at":"2019-07-29T03:18:18.051073+02:00","index":3,"serial":"xxx","name":"xxx","memory":xxx},{"uuid":"a8bbfc9a09d844b987273ce068bb86bb","cluster_node":"63a0e26f2a0b40fe8cc9d6f5d635fa29","created_at":"2019-07-25T10:37:31.482774+02:00","updated_at":"2019-07-29T03:18:18.058984+02:00","index":4,"serial":"xxx","name":"xxx","memory":xxx},{"uuid":"d964e53c5b5640b59d5c412650279f55","cluster_node":"63a0e26f2a0b40fe8cc9d6f5d635fa29","created_at":"2019-07-25T10:37:31.497678+02:00","updated_at":"2019-07-29T03:18:18.066892+02:00","index":5,"serial":"xxx","name":"xxx","memory":xxx},{"uuid":"d89f5311b281430b97edb8648b7bee61","cluster_node":"63a0e26f2a0b40fe8cc9d6f5d635fa29","created_at":"2019-07-25T10:37:31.512361+02:00","updated_at":"2019-07-29T03:18:18.075009+02:00","index":6,"serial":"xxx","name":"xxx","memory":xxx},{"uuid":"9e55405344e04c8b90dc67767b8c5c07","cluster_node":"63a0e26f2a0b40fe8cc9d6f5d635fa29","created_at":"2019-07-25T10:37:31.528068+02:00","updated_at":"2019-07-29T03:18:18.082870+02:00","index":7,"serial":"xxx","name":"xxx","memory":xxx}],"sequence":1,"name":"xxx","hostname":"xxx","role":"agent","docker_version":"18.3.1","kubelet_version":"v1.12.2","os_image":"CentOS Linux 7 (Core)","kernel_version":"3.10.0-957.1.3.el7.x86_64","schedulable_taints":true,"schedulable_state":true,"memory":xxx,"cpu":16.0,"n_gpus":8,"status":"ready","is_current":true}', Headers: {'Server': 'nginx/1.10.3', 'Date': 'Mon, 29 Jul 2019 01:18:18 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Allow': 'GET, PUT, PATCH, DELETE, HEAD, OPTIONS', 'X-Frame-Options': 'SAMEORIGIN', 'Vary': 'Origin, Cookie', 'Content-Encoding': 'gzip'}
Sending message of length 5330 to https://sentry.io/api/1197416/store/
Traceback (most recent call last):
  File "/opt/polyaxon_cli/bin/polyaxon", line 11, in <module>
    sys.exit(cli())
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_cli/logger.py", line 56, in clean_outputs_wrapper
    raise e
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_cli/logger.py", line 50, in clean_outputs_wrapper
    return fn(*args, **kwargs)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_cli/cli/cluster.py", line 56, in cluster
    node_config = cluster_client.get_node(node)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_client/api/cluster.py", line 29, in get_node
    return self.prepare_results(response_json=response.json(), config=ClusterNodeConfig)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_client/api/base.py", line 69, in prepare_results
    if self.config.schema_response else response_json)
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/polyaxon_schemas/base.py", line 117, in from_dict
    return cls.SCHEMA(unknown=unknown).load(value)  # pylint: disable=not-callable
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/marshmallow/schema.py", line 706, in load
    postprocess=True,
  File "/opt/polyaxon_cli/lib/python3.6/site-packages/marshmallow/schema.py", line 866, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'gpus': {0: {'updated_at': ['Unknown field.'], 'created_at': ['Unknown field.']}, 1: {'updated_at': ['Unknown field.'], 'created_at': ['Unknown field.']}, 2: {'updated_at': ['Unknown field.'], 'created_at': ['Unknown field.']}, 3: {'updated_at': ['Unknown field.'], 'created_at': ['Unknown field.']}, 4: {'updated_at': ['Unknown field.'], 'created_at': ['Unknown field.']}, 5: {'updated_at': ['Unknown field.'], 'created_at': ['Unknown field.']}, 6: {'updated_at': ['Unknown field.'], 'created_at': ['Unknown field.']}, 7: {'updated_at': ['Unknown field.'], 'created_at': ['Unknown field.']}}}
```

**Comment by mouradmourafiq** [comment]
This command was removed completely.
