### ISSUE TITLE
Polyaxon pytorch-mnist example running error(The docker image could not be pushed.)

### ISSUE THREAD

**Issue by dongdan39** [polyaxon/polyaxon#575]
Hi, Expert,
  I have installed successfully polyaxon 0.5.6 on my local kubernetes 1.15.2 cluster. Now when I'm trying to run the polyaxonfile_hyperparams.yml example as stated on:
https://extrapolations.dev/blog/2018/10/model-management-polyaxon-argo-seldon/

I get the following build error. I have set up local docker registry which IP is 192.168.111.118,
test by hand that login/pull/push to the registry all works fine. But in the log I see the code tried to tag and push docker images refering to 127.0.0.1:31813/v2, why this happened? I checked that in my docker /etc/docker/daemon.json the correct entry is there:
  "insecure-registries": [
      "192.168.111.118"
  ],

Any help will be appreciated!
Cheers,
Dan

2019-09-19 08:03:04 UTC -- Building: Step 1/5 : FROM 192.168.111.118/library/pytorch:latest

2019-09-19 08:03:04 UTC -- Building:

2019-09-19 08:03:04 UTC -- Pushing ...

2019-09-19 08:03:04 UTC -- Building: ---> 255eed982b39

2019-09-19 08:03:04 UTC -- Building: Step 2/5 : ENV SHELL /bin/bash

2019-09-19 08:03:04 UTC -- Building:

2019-09-19 08:03:04 UTC -- Building: ---> Using cache

2019-09-19 08:03:04 UTC -- Building: ---> dc3583198707

2019-09-19 08:03:04 UTC -- Building: Step 3/5 : WORKDIR /code

2019-09-19 08:03:04 UTC -- Building:

2019-09-19 08:03:04 UTC -- Building: ---> Using cache

2019-09-19 08:03:04 UTC -- Building: ---> 64d428d6467a

2019-09-19 08:03:04 UTC -- Building: Step 4/5 : RUN pip install --no-cache-dir -U polyaxon-helper

2019-09-19 08:03:04 UTC -- Building:

2019-09-19 08:03:04 UTC -- Building: ---> Using cache

2019-09-19 08:03:04 UTC -- Building: ---> b07c37c593cb

2019-09-19 08:03:04 UTC -- Building: Step 5/5 : COPY build /code

2019-09-19 08:03:04 UTC -- Building:

2019-09-19 08:03:04 UTC -- Building: ---> Using cache

2019-09-19 08:03:04 UTC -- Building: ---> f734aeed8bab

2019-09-19 08:03:04 UTC -- Pushing finished: {'ID': 'sha256:f734aeed8babd1a786622db6380c53bbf29744210a0c794e7eb8d5bfb9a9c07a'}

2019-09-19 08:03:04 UTC -- Building: Successfully built f734aeed8bab

2019-09-19 08:03:04 UTC -- Building: Successfully tagged 127.0.0.1:31813/mnist_3:8d27d4a47c704312a71a0dfb7324a63d

2019-09-19 08:03:34 UTC -- ERROR: Get http://127.0.0.1:31813/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

2019-09-19 08:03:34 UTC -- Traceback (most recent call last):

2019-09-19 08:03:34 UTC --   File "dockerizer/build_cmd.py", line 38, in <module>

2019-09-19 08:03:34 UTC --     nocache=nocache)

2019-09-19 08:03:34 UTC --   File "/usr/local/lib/python3.7/site-packages/polyaxon_dockerizer/builder.py", line 239, in build_and_push

2019-09-19 08:03:34 UTC --     push(docker_builder, max_retries=max_retries, sleep_interval=sleep_interval)

2019-09-19 08:03:34 UTC --   File "/usr/local/lib/python3.7/site-packages/polyaxon_dockerizer/builder.py", line 207, in push

2019-09-19 08:03:34 UTC --     raise BuildException('The docker image could not be pushed.')

2019-09-19 08:03:34 UTC -- polyaxon_dockerizer.exceptions.BuildException: The docker image could not be pushed.

**Comment by mouradmourafiq** [comment]
You can try to use a build a kaniko backend to see if it works. `backend: kaniko`

**Comment by dongdan39** [comment]
@mouradmourafiq, could you describe it a bit more? Not clear what are the steps.

**Comment by mouradmourafiq** [comment]
The integration docs: https://docs.polyaxon.com/integrations/kaniko/

In other terms, you can update the build section to specify a different backend:
```yaml
...
build:
 backend: kaniko
 image: pytorch/pytorch:latest
 build_steps:
   - pip install --no-cache-dir -U polyaxon-helper

...
```

**Comment by dongdan39** [comment]
@mouradmourafiq, thanks a lot! The issue here is how to set the default local registry to push a docker image we build in the polyaxon experiments. If I only set "backend: kaniko" in the build, how it can know which registry to use to tag and push the images?

**Comment by mouradmourafiq** [comment]
https://docs.polyaxon.com/configuration/docker-registry-ha/

**Comment by dongdan39** [comment]
@mouradmourafiq, Thanks for the link! I tried both "true" and "false" to the following setting in polyaxon-config.yml file and redeployed the polyaxon platform, but the experiments all failed as before.  The experiment still tries to tag and push docker images refering to 127.0.0.1:31813/v2
instead of my private docker registry.(I configured it in "Registries" on the dashboard). What's the problem?

docker-registry:
  enabled: false

Cheers,
Dan

**Comment by mouradmourafiq** [comment]
The config: 
```
docker-registry:
  enabled: false
```
Tells polyaxon to not deploy the in-cluster registry, which I think is what you want.

In the UI, you need to add a new registry, and you need to mark it as default using the dropdown to the right.

**Comment by dongdan39** [comment]
@mouradmourafiq, Thanks a lot! Now I can see in the log that the job tries to access the right private docker registry! However, the build still failed with:

  Normal   Scheduled    25m                   default-scheduler        Successfully assigned polyaxon/plx-build-8a2574d136bd42c8916964f17b856033 to kube-cluster-5
  Warning  FailedMount  3m1s (x10 over 23m)   kubelet, kube-cluster-5  Unable to mount volumes for pod "plx-build-8a2574d136bd42c8916964f17b856033_polyaxon(14a608c7-335d-4565-8228-5e7179b9aa13)": timeout expired waiting for volumes to attach or mount for pod "polyaxon"/"plx-build-8a2574d136bd42c8916964f17b856033". list of unmounted volumes=[docker-credentials]. list of unattached volumes=[docker build-context docker-credentials polyaxon-polyaxon-workers-serviceaccount-token-bd2z8]
  Warning  FailedMount  2m57s (x19 over 25m)  kubelet, kube-cluster-5  **MountVolume.SetUp failed for volume "docker-credentials" : secret "regcred" not found**

I have create the secret "regcred" already:
# kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
{"auths":{"192.168.111.118":{"username":"admin","password":"XXXXXXXX","email":"XXXXX@YYY.com","auth":"YWRtzcp9aW4Ym9yrwNh"}}}

Should I also create a volume "docker-credentials"  for secret "regcred" ? Thanks!

Cheers,
Dan

**Comment by dongdan39** [comment]
Close to create a new issue.
