### ISSUE TITLE
Error when upgrading deployment for ldap integration

### ISSUE THREAD

**Issue by flaviosakakibara** [polyaxon/polyaxon#592]
### Describe the bug
An error occurs when trying to upgrade a polyaxon deployment in order to run with ldap integration.

Occured Error:
```
Traceback (most recent call last):
  File "/polyaxon/polyaxon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/polyaxon/polyaxon/polyaxon/settings.py", line 1, in <module>
    from polyaxon.config_settings import *  # noqa
  File "/polyaxon/polyaxon/polyaxon/config_settings/__init__.py", line 22, in <module>
    from .monolith import *
  File "/polyaxon/polyaxon/polyaxon/config_settings/monolith/__init__.py", line 2, in <module>
    from polyaxon.config_settings.auth import *
  File "/polyaxon/polyaxon/polyaxon/config_settings/auth.py", line 75, in <module>
    group_type[0].upper() + group_type[1:] + 'Type')()
AttributeError: module 'django_auth_ldap.config' has no attribute '(objectClass=groupOfUniqueNames)Type'
```

### To Reproduce

1 -> get a working instance of polyaxon without ldap configuration using helm install;
2 -> use a helm upgrade command using the -f directive to add ldap values to the working deployment. 

### Expected behavior
polyaxon running integrated with company's ldap.

### Environment
The deployment is being done on a k8s cluster (running over centos vms).
Follows the values used for the ldap deloyment:
```
ldap:
  bindDN: uid=bind_user,ou=bind,ou=usuarios,ou=acesso,o=org,C=BR
  bindPassword: bindPassword
  connectionOptions: {}
  enabled: true
  globalOptions: {}
  groupSearchBaseDN: ou=aplicacao,ou=grupos,ou=acesso,o=org,C=BR
  groupSearchGroupType: (objectClass=groupOfUniqueNames)
  serverUri: ldaps://ldap_uri:636
  startTLS: true
  userAttrMap:
    first_name: givenName
    last_name: sn
  userDNTemplate: uid=%(user)s,ou=funcionarios,ou=usuarios,ou=acesso,o=org,C=BR
  userSearchBaseDN: ou=usuarios,ou=acesso,o=org,C=BR
  userSearchFilterStr: (uid=%(user)s)
  requireGroup: 'cn=disabled,ou=groups,dc=example,dc=com'
  denyGroup: 'cn=disabled,ou=groups,dc=example,dc=com'
```

**Comment by mv3eng** [comment]
In manual polyaxon there is an error in the configuration example, 
in **groupSearchGroupType** you just need to pass the name of objectClasse. 


> groupOfUniqueNames

 instead 

> objectClass=groupOfUniqueNames.

groupSearchGroupType: (objectClass=groupOfUniqueNames)

I made a configuration using open ldap, 



ldap:
  enabled: true
  serverUri: "ldap://openldap:389"
  globalOptions: {}
  connectionOptions: {}
  bindDN:  'cn=admin,dc=example,dc=org'
  bindPassword: '9wKg8e2070ua6BrAiPhvToodJiYZaE8X'
  userSearchBaseDN:  'ou=users,dc=example,dc=org'
  userSearchFilterStr: '(uid=%(user)s)'
  userDNTemplate: 'cn=%(user)s,ou=users,dc=example,dc=org'
  startTLS: false
  userAttrMap: {'first_name': 'givenName', 'last_name': 'sn'}
  groupSearchBaseDN: 'dc=example,dc=org'
  groupSearchGroupType: 'GroupOfNames'
  requireGroup:  
  denyGroup:

**Comment by mouradmourafiq** [comment]
Closing this issue as wontfix. Similar reason as #698.
