### ISSUE TITLE
Foreign key constraint error in logs

### ISSUE THREAD

**Issue by stratospark** [polyaxon/polyaxon#603]
I'm seeing a bunch of errors like the one below in the polyaxon scheduler logs. Is there a reason the database gets into this state, and is there an easy way to fix this? I am using polyaxon 0.5.6

```
[2019-11-12 21:00:54,063: ERROR/ForkPoolWorker-4711] Task delete_archived_experiment_group[741596d6-374b-4af1-8b08-7f4c390d616a] raised unexpected: IntegrityError('update or delete on table "db_experiment" violates foreign key constraint "db_experimentstatus_experiment_id_e38fa13a_fk_db_experiment_id" on table "db_experimentstatus"\nDETAIL:  Key (id)=(4203) is still referenced from table "db_experimentstatus".\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
psycopg2.IntegrityError: update or delete on table "db_experiment" violates foreign key constraint "db_experimentstatus_experiment_id_e38fa13a_fk_db_experiment_id" on table "db_experimentstatus"
DETAIL:  Key (id)=(4203) is still referenced from table "db_experimentstatus".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/polyaxon/polyaxon/scheduler/tasks/deletion.py", line 24, in delete_archived_experiment_group
    ExperimentGroup.archived.get(id=group_id).delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 919, in delete
    return collector.delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/deletion.py", line 318, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/local/lib/python3.7/site-packages/django/db/transaction.py", line 240, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: update or delete on table "db_experiment" violates foreign key constraint "db_experimentstatus_experiment_id_e38fa13a_fk_db_experiment_id" on table "db_experimentstatus"
DETAIL:  Key (id)=(4203) is still referenced from table "db_experimentstatus".
```

**Comment by mouradmourafiq** [comment]
I think this  could occur when an error in the cron deletion task happens, and because there's a retry the task never finishes. The task must be manually removed from scheduler's queue. This is an annoying bug, and is related to #526 or could happen because of that issue.
