### ISSUE TITLE
Cannot build experiment - Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by boniek83** [polyaxon/polyaxon#669]
### Describe the bug
When trying to run any project:
```
2020-01-23 17:37:20 UTC -- ERROR: Could not build the image, encountered 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: Dockerfile")

2020-01-23 17:37:20 UTC -- Traceback (most recent call last):

2020-01-23 17:37:20 UTC --   File "dockerizer/build_cmd.py", line 38, in <module>

2020-01-23 17:37:20 UTC --     nocache=nocache)

2020-01-23 17:37:20 UTC --   File "/usr/local/lib/python3.7/site-packages/polyaxon_dockerizer/builder.py", line 238, in build_and_push

2020-01-23 17:37:20 UTC --     sleep_interval=sleep_interval)

2020-01-23 17:37:20 UTC --   File "/usr/local/lib/python3.7/site-packages/polyaxon_dockerizer/builder.py", line 189, in build

2020-01-23 17:37:20 UTC --     registries=registries)

2020-01-23 17:37:20 UTC --   File "/usr/local/lib/python3.7/site-packages/polyaxon_dockerizer/builder.py", line 167, in _build

2020-01-23 17:37:20 UTC --     raise BuildException('The docker image could not be built.')

2020-01-23 17:37:20 UTC -- polyaxon_dockerizer.exceptions.BuildException: The docker image could not be built.
```

I would appreciated some tips why that happens and how to fix or debug this.

### To Reproduce
I can reproduce it everytime on my side, but it worked before - no idea what changed.
### Expected behavior
Build should pass.
### Environment
polyaxon 0.5.6
native or kaniko backend - doesn't matter

**Comment by boniek83** [comment]
Uprading to 0.6.0 helped.
