### ISSUE TITLE
Hidden conflict from pathlib

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#675]
### Describe the bug
Installing latest `polyaxon-cli` breaks `allennlp` framework with no explicit conflicts. The package `polyaxon-cli` is using `pathlib=1.0.1` - https://github.com/polyaxon/polyaxon/blob/master/cli/requirements/requirements-base.txt. When I install package `polyaxon-cli` and `allennlp`, I cannot train models locally due the following error. I believe it's because `pathlib` from standard libary (introduced in Python 3.4) conflicts with this package. 

```
Traceback (most recent call last):
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/catalogue.py", line 8, in <module>
    import importlib.metadata as importlib_metadata
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/allennlp/run.py", line 14, in <module>
    from allennlp.commands import main  # noqa
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/allennlp/__init__.py", line 18, in <module>
    import spacy, torch, numpy  # noqa
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/spacy/__init__.py", line 12, in <module>
    from . import pipeline
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/spacy/pipeline/__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 1, in init spacy.pipeline.pipes
  File "strings.pxd", line 23, in init spacy.syntax.nn_parser
  File "strings.pyx", line 17, in init spacy.strings
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/spacy/util.py", line 16, in <module>
    import catalogue
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/catalogue.py", line 10, in <module>
    import importlib_metadata
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 591, in <module>
    __version__ = version(__name__)
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 553, in version
    return distribution(distribution_name).version
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 253, in version
    return self.metadata['Version']
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 241, in metadata
    self.read_text('METADATA')
  File "/home/pi3ni0/.venv/dev/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 513, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'PosixPath' object has no attribute 'read_text'

Process finished with exit code 1

```

Uninstalling `pathlib=1.0.1` removes exception, but I don't know how it affects training in the Polyaxon environment.

### Environment
- python 3.6.9
- polyaxon-cli 0.6.0
- allennlp 0.9.1-unreleased

**Comment by mouradmourafiq** [comment]
Will check if it's necessary to keep that dependency around, otherwise we can remove it.

If you are using polyaxon inside your training script (for tracking and apis), install `polyaxon-client` in stead of `polyaxon-cli` and it should work.

**Comment by mouradmourafiq** [comment]
I assume that you fixed the issue by installing polyaxon-client instead of polyaxon-cli.

I will close the issue, feel free to reopen if you still have questions. One more thing, `pathlib` is completely removed in v1.

**Comment by mateuszpieniak** [comment]
I've just uninstalled `pathlib` library and it works.

czw., 13 lut 2020 o 22:22 Mourad <notifications@github.com> napisał(a):
