### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by kairos03** [polyaxon/polyaxon#678]
Hi,

i'm installing polyaxon with helm all other pods is available but api-server and scheduler causing error.
Any one help me?

OS : ubuntu 18.04.3
k8s: 1.15.0
helm: 2.16.1

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 35, in check_url_namespaces_unique
    if not getattr(settings, 'ROOT_URLCONF', None):
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/polyaxon/polyaxon/polyaxon/__init__.py", line 1, in <module>
    from polyaxon.celery_api import app
  File "/polyaxon/polyaxon/polyaxon/celery_api.py", line 3, in <module>
    from celery import Celery, states
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/usr/local/lib/python3.7/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.7/site-packages/celery/utils/__init__.py", line 9, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/usr/local/lib/python3.7/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "/usr/local/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/usr/local/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 23, in <module>
    from kombu import exceptions
  File "/usr/local/lib/python3.7/site-packages/kombu/exceptions.py", line 6, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.7/site-packages/amqp/__init__.py", line 33, in <module>
    from .connection import Connection  # noqa
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 21, in <module>
    from .transport import Transport
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 8, in <module>
    import ssl
  File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/polyaxon/polyaxon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/polyaxon/polyaxon/polyaxon/__init__.py", line 1, in <module>
    from polyaxon.celery_api import app
  File "/polyaxon/polyaxon/polyaxon/celery_api.py", line 3, in <module>
    from celery import Celery, states
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/usr/local/lib/python3.7/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.7/site-packages/celery/utils/__init__.py", line 9, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/usr/local/lib/python3.7/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "/usr/local/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/usr/local/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 23, in <module>
    from kombu import exceptions
  File "/usr/local/lib/python3.7/site-packages/kombu/exceptions.py", line 6, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.7/site-packages/amqp/__init__.py", line 33, in <module>
    from .connection import Connection  # noqa
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 21, in <module>
    from .transport import Transport
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 8, in <module>
    import ssl
  File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
Running...
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/celery/__main__.py", line 15, in main
    from celery.bin.celery import main as _main
  File "/usr/local/lib/python3.7/site-packages/celery/bin/__init__.py", line 2, in <module>
    from .base import Option
  File "/usr/local/lib/python3.7/site-packages/celery/bin/base.py", line 16, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency, signals
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/usr/local/lib/python3.7/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.7/site-packages/celery/utils/__init__.py", line 9, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/usr/local/lib/python3.7/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "/usr/local/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/usr/local/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 23, in <module>
    from kombu import exceptions
  File "/usr/local/lib/python3.7/site-packages/kombu/exceptions.py", line 6, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.7/site-packages/amqp/__init__.py", line 33, in <module>
    from .connection import Connection  # noqa
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 21, in <module>
    from .transport import Transport
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 8, in <module>
    import ssl
  File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)

```

**Comment by kairos03** [comment]
No, I'm using on-premise setting.

**Comment by mouradmourafiq** [comment]
what polyaxon version are you deploying? This is a weird error, since the containers should contain all necessary libraries.

**Comment by kairos03** [comment]
I'm using `polyaxon-0.6.0` install with helm.

I install with following instruction.
```
# helm install polyaxon --namespace polyaxon -f config.yaml polyaxon/polyaxon
```

and use this config file
```
namespace: polyaxon

rbac:
  enabled: false
ingress:
  enabled: false

serviceType: NodePort

timeZone: Asia/Seoul

dirs:
  nvidia:
    lib: "/usr/lib"  # e.g. "/usr/lib/nvidia-384"
    bin: "/usr/bin"  # e.g. "/usr/lib/nvidia-384/bin"
    libcuda: "/usr/lib/x86_64-linux-gnu/libcuda.so"  # e.g. "/usr/lib/x86_64-linux-gnu/libcuda.so.1"

persistence:
  data:
    dataset:
      mountPath: "/dataset"
      existingClaim: "polyaxon-dataset"
      readOnly: true
    data:
      mountPath: "/data"
      hostPath: "/data"
  outputs:
    outputs:
      mountPath: "/outputs"
      hostPath: "polyaxon-outputs"

```

**Comment by mouradmourafiq** [comment]
Seems like some version mismatch, see this [SO answer](https://stackoverflow.com/questions/59105412/python-in-ubuntu-16-04-lts-gives-error-lib-x86-64-linux-gnu-libc-so-6-version?answertab=votes#tab-top)

**Comment by kairos03** [comment]
I install python3.7 to all nodes but it is not work for me.

So, I'm trying to directly install glibc-2.25.

**Comment by stefankraft** [comment]
I am running into the same problem however just with the scheduler pod.
k8s: 1.17.0
helm: 3.0.3
OS of scheduler pod node: Ubuntu 18.04.4

Is this actually a problem within the container (which would be strange as mouradmourafiq has noted) or of the hosting node?

**Comment by kairos03** [comment]
I fixed this issue to remove `dirs` section of config file. @stefankraft

**Comment by kairos03** [comment]
Bu, I dumped in another issue that api server fail to health check for liveness and readness.

**Comment by stefankraft** [comment]
Thanks @kairos03 this worked for me as well. I suppose that this is only a temporary solution though since we want to perform calculations on GPU nodes in the next step.
So the question is: Why does this error occur when defining the Nvidia paths?

**Comment by kairos03** [comment]
I'm using 2080ti and 440 driver.
Actually, I cannot  found the NVidia path. :(
I think ask to slack about this problem is better. May be someone can share the config to us.
@stefankraft

**Comment by stefankraft** [comment]
We could solve the problem, we had to provide the correct links to the Nvidia libraries

**Comment by QipengZhou** [comment]
The problem is because your `config.yaml`
```
dirs:
  nvidia:
    lib: "/usr/lib"  # e.g. "/usr/lib/nvidia-384"
    bin: "/usr/bin"  # e.g. "/usr/lib/nvidia-384/bin"
    libcuda: "/usr/lib/x86_64-linux-gnu/libcuda.so"  # e.g. "/usr/lib/x86_64-linux-gnu/libcuda.so.1"
````
this will generate environment `LD_LIBRARY_PATH`, and this will change link lib path. `dirs` is your host nvidia directory, if you not set `mountPaths` it is your mount path in pod. A solution is:
1. change your `config.yaml`
```
dirs:
  nvidia:
    lib: "/usr/local/polyaxon-nvidia"  # e.g. "/usr/lib/nvidia-384"
    bin: "/usr/local/polyaxon-nvidia/bin"  # e.g. "/usr/lib/nvidia-384/bin"
    libcuda: "/usr/local/polyaxon-nvidia"  # e.g. "/usr/lib/x86_64-linux-gnu/libcuda.so.1"
mountPaths:
  nvidia:
     lib: /usr/local/nvidia-lib
     bin: /usr/local/nvidia-bin
     libcuda: /usr/local/nvidia-cuda
```
2. use `/usr/local/polyaxon-nvidia` in your host because some nvidia install in `/usr/lib64`, it will throw `GLIBC` not found if mount host `/usr/lib64` to k8s pod directory(this directory in `LD_LIBRARY_PATH`). `->` is a soft link by `ln -s`. `bin` only include `nvidia-smi`.
```bash
$ ls /usr/local/polyaxon-nvidia
bin
libcuda.so -> libcuda.so.410.78
libcuda.so.1 -> libcuda.so.410.78
libcuda.so.410.78
libnvidia-fatbinaryloader.so.410.78
libnvidia-ml.so -> libnvidia-ml.so.410.78
libnvidia-ml.so.1 -> libnvidia-ml.so.410.78
libnvidia-ml.so.410.78
```
