### ISSUE TITLE
User deletion doesn't work

### ISSUE THREAD

**Issue by boniek83** [polyaxon/polyaxon#698]
### Describe the bug
When trying to delete user polyaxon spews an error:
`[pid: 205|app: 0|req: 266/1062] 10.34.186.132 () {70 vars in 1496 bytes} [Mon Mar 30 14:00:13 2020] POST /_admin/db/user/115/delete/ => generated 0 bytes in 130 msecs (HTTP/1.1 405) 7 headers in 269 bytes (1 switches on core 0)
WARNING 2020-03-30 14:01:05,369 base 204 140141628552960 Method Not Allowed (POST): /_admin/db/user/115/delete/
WARNING 2020-03-30 14:01:05,370 log 204 140141628552960 Method Not Allowed: /_admin/db/user/115/delete/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1838, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1868, in _delete_view
    self.delete_model(request, obj)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1094, in delete_model
    obj.delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 919, in delete
    return collector.delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/deletion.py", line 318, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/hestia/signal_decorators.py", line 24, in __call__
    return self.f(*args, **kwargs)
  File "/polyaxon/web/../polyaxon/signals/users.py", line 36, in delete_user_owner
    ownership.delete_owner(name=instance.username)
  File "/usr/local/lib/python3.7/site-packages/hestia/service_interface.py", line 70, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/polyaxon/web/../polyaxon/ownership/service.py", line 106, in delete_owner
    self.owner_manager.get(name=name).delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 919, in delete
    return collector.delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/deletion.py", line 289, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/hestia/signal_decorators.py", line 24, in __call__
    return self.f(*args, **kwargs)
  File "/polyaxon/web/../polyaxon/signals/deletion.py", line 185, in project_pre_delete
    delete_project_repos(instance.unique_name)
  File "/polyaxon/web/../polyaxon/db/models/projects.py", line 71, in unique_name
    user=self.user.username,
AttributeError: 'NoneType' object has no attribute 'username'`

### Environment
Polyaxon 0.6.1, Kubernetes 1.15.9 on premise.

**Comment by mouradmourafiq** [comment]
A much better interface will be exposed for open source users to use their own user management.
