### ISSUE TITLE
Experiment sidecar dies when kube-proxy is restarted

### ISSUE THREAD

**Issue by mengxi-ascent** [polyaxon/polyaxon#699]
### Describe the bug
When the `kube-proxy` are restarted in k8s, experiment sidecars will die due to connection errors. After a while, the experiments are marked as in the zombie state and deleted by polyaxon.

Here is the logs from the `polyxon-monitor`, which are similar to the logs of dead sidecars:
```
ERROR 2020-03-31 04:28:09,974 monitor_statuses 18 140255593842432 Unhandled exception occurred ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 685, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 752, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 689, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/polyaxon/polyaxon/monitor_statuses/management/commands/monitor_statuses.py", line 29, in handle
    monitor.run(k8s_manager)
  File "/polyaxon/polyaxon/monitor_statuses/monitor.py", line 156, in run
    watch_ttl=watch_ttl):
  File "/usr/local/lib/python3.7/site-packages/ocular/__init__.py", line 68, in monitor
    watch_ttl):
  File "/usr/local/lib/python3.7/site-packages/ocular/__init__.py", line 29, in _monitor
    **params):
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 144, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 48, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 781, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2020-03-31 04:28:10,019 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8fb36e3590>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/polyaxon/pods?labelSelector=role+in+%28polyaxon-workers%2Cpolyaxon-dashboard%29%2Ctype%3Dpolyaxon-runner&resourceVersion=3369854&timeoutSeconds=1200&watch=True
2020-03-31 04:28:10,021 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8fb2fe9210>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/polyaxon/pods?labelSelector=role+in+%28polyaxon-workers%2Cpolyaxon-dashboard%29%2Ctype%3Dpolyaxon-runner&resourceVersion=3369854&timeoutSeconds=1200&watch=True
2020-03-31 04:28:10,023 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8fb3018890>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/polyaxon/pods?labelSelector=role+in+%28polyaxon-workers%2Cpolyaxon-dashboard%29%2Ctype%3Dpolyaxon-runner&resourceVersion=3369854&timeoutSeconds=1200&watch=True
2020-03-31 04:28:11,030 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8fb36c0890>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/polyaxon/pods?labelSelector=role+in+%28polyaxon-workers%2Cpolyaxon-dashboard%29%2Ctype%3Dpolyaxon-runner&resourceVersion=3369854&timeoutSeconds=1200&watch=True
2020-03-31 04:28:11,033 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8fb33cb890>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/polyaxon/pods?labelSelector=role+in+%28polyaxon-workers%2Cpolyaxon-dashboard%29%2Ctype%3Dpolyaxon-runner&resourceVersion=3369854&timeoutSeconds=1200&watch=True
```

### To Reproduce
1. Run an experiment in Polyaxon.
2. When the experiment is running, restart `kube-proxy` of k8s. (By deleting the pods and letting k8s re-create the pods with daemonset)

### Expected behavior
Expect the sidecar to restart or re-connect after the `kube-proxy` is ready again.

### Environment
Azure AKS, Polyaxon v0.6.1

**Comment by mouradmourafiq** [comment]
This is more or less similar to #695 and is already solved in v1.
Thanks for reporting the issue.
