### ISSUE TITLE
Upgrade to v0.6.1 failure

### ISSUE THREAD

**Issue by ajuric** [polyaxon/polyaxon#709]
### Describe the bug

Cannot start the Polyaxon when trying to run v0.6.1 (from 0.6.0). There is an error in postgresql db saying that polyaxon user/role is missing:
```
kubectl -n polyaxon logs polyaxon-postgresql-0 | head -n 50
postgresql 11:08:19.45 
postgresql 11:08:19.46 Welcome to the Bitnami postgresql container
postgresql 11:08:19.46 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 11:08:19.46 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 11:08:19.46 Send us your feedback at containers@bitnami.com
postgresql 11:08:19.46 
postgresql 11:08:19.48 INFO  ==> ** Starting PostgreSQL setup **
postgresql 11:08:19.55 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 11:08:19.55 INFO  ==> Loading custom pre-init scripts...
postgresql 11:08:19.56 INFO  ==> Initializing PostgreSQL database...
postgresql 11:08:19.56 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql 11:08:19.58 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 11:08:19.59 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 11:08:19.59 INFO  ==> Generating local authentication configuration
postgresql 11:08:19.61 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 11:08:19.61 INFO  ==> Configuring replication parameters
postgresql 11:08:19.64 INFO  ==> Configuring fsync
postgresql 11:08:19.69 INFO  ==> Loading custom scripts...
postgresql 11:08:19.70 INFO  ==> Enabling remote connections
postgresql 11:08:19.71 INFO  ==> Stopping PostgreSQL...

postgresql 11:08:19.71 INFO  ==> ** PostgreSQL setup finished! **
postgresql 11:08:19.78 INFO  ==> ** Starting PostgreSQL **
2020-04-15 11:08:19.894 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-04-15 11:08:19.894 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-04-15 11:08:19.942 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-04-15 11:08:20.237 GMT [170] LOG:  database system was interrupted; last known up at 2020-04-15 11:08:06 GMT
2020-04-15 11:08:22.228 GMT [170] LOG:  database system was not properly shut down; automatic recovery in progress
2020-04-15 11:08:22.299 GMT [170] LOG:  redo starts at 0/1657F18
2020-04-15 11:08:22.300 GMT [170] LOG:  invalid record length at 0/1657FC0: wanted 24, got 0
2020-04-15 11:08:22.300 GMT [170] LOG:  redo done at 0/1657F50
2020-04-15 11:08:22.576 GMT [1] LOG:  database system is ready to accept connections
2020-04-15 11:08:29.540 GMT [184] FATAL:  password authentication failed for user "polyaxon"
2020-04-15 11:08:29.540 GMT [184] DETAIL:  Role "polyaxon" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
2020-04-15 11:08:30.684 GMT [185] FATAL:  password authentication failed for user "polyaxon"
```

### To Reproduce

I have restarted my k8s (kubeadm server) with `sudo kubeadm reset` and tried to deploy new Polyaxon ...

I have tried the whole process a couple of times. At some of there tries (perhaps the first one), I had no free memory, unfortunately ... So I had to stop the process of deployment. Maybe this interception broke something? If so, is my only way out to start the Polyaxon without "old data" (from the scratch)?

Also, when I try to run the old version of Polyaxon (0.6.0), there are errors in containers named something like admin-user-sync ... saying something like:
Got 3 users, expected 1 (when trying to catch from db ...)

I don't have correct names and the error output for the above currently, but I can send if needed.

### Expected behavior

Not quite sure since in the release notes is says: "IMPORTANT: If you are using the built-in database you cannot upgrade automatically."

### Environment

Kubeadm v1.11.1
Ubuntu 16.04
Docker 18.06.1-ce

**Comment by mouradmourafiq** [comment]
Hi @ajuric I answered this in the slack channel, [link](https://polyaxon.slack.com/archives/CA5N9DDGE/p1585156788004200?thread_ts=1585144772.003300&cid=CA5N9DDGE)

The [v0.6.1 release notes](https://github.com/polyaxon/polyaxon/releases/tag/0.6.1) have also an important note:  `If you are using the built-in database you cannot upgrade automatically.`

Unfortunately this is something out of the scope of Polyaxon.

**Comment by ajuric** [comment]
Hi @mouradmourafiq 

Thank you for the fast reply. I checked the Slack before posting here, but didn't find the link you send, thanks!

As I said, I saw the note you mention. I guess that it would help users if it also said that there are procedures for migrating between postgresql versions (at least I didn't know that).

These links helped me:
* https://stackoverflow.com/questions/24379373/how-to-upgrade-postgresql-from-version-9-6-to-version-10-1-without-losing-data
* https://geekforum.wordpress.com/2014/05/31/upgrade-postgresql-package/
* https://github.com/tianon/docker-postgres-upgrade/blob/master/9.6-to-11/Dockerfile
* https://github.com/tianon/docker-postgres-upgrade/issues/14

I managed to resolve this and start PLX.

But, I had some other errors, connected with the problem I described above (memory full ...). So I went to starting PLX from scratch (no "old data") to avoid DB migration. Unfortunately, I have again received an error: while running `helm install polyaxon ...`, the `polyaxon-sync-db` pod fails with the message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "polyaxon"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "polyaxon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "polyaxon"

```

Is this expected or?

**Comment by mouradmourafiq** [comment]
> I guess that it would help users if it also said that there are procedures for migrating between postgresql versions (at least I didn't know that).

This is my bad, the note about no automatic migration meant that there's no handling for migrating the db schema/index from one version to another.

But I agree, I should have mentioned that following the pgsql docs one can do that, or if the user is using a cloud pgsql the cloud providers have generally that option.

The migration is generally painful, and gets complicated with more data, and can take a day or more if there's a large amount of data, that's why you have memory issues.

> FATAL:  password authentication failed for user "polyaxon"

Did set a different password for the db.

**Comment by ajuric** [comment]
> Did set a different password for the db.

Where this should be changed? In polyaxon deployment config?

I didn't change anything in polyaxon deployment config, just tried to start PLX with the same config. (and no old data ...)

**Comment by mouradmourafiq** [comment]
weird, the default password in the values is polyaxon. How was the db pod created? is it coming from the upgrade or is it 100% new based on the new chart?

**Comment by ajuric** [comment]
I guess you mean this one: https://github.com/polyaxon/polyaxon-charts/blob/master/polyaxon/values.yaml#L280

No, it's not coming from the upgrade. I deleted all old data, and started PLX fresh.

**Comment by mouradmourafiq** [comment]
yes, that's the default password. If you deploy with postgres persistence, it might load some data from that persistent layer.

Another option, could be to run kubectl exec to get to the db pod and run some queries to check what user was created.

**Comment by mouradmourafiq** [comment]
but this is weird, the user polyaxon, and the password is wrong?

**Comment by mouradmourafiq** [comment]
actually there's this line: `Role "polyaxon" does not exist.` in the logs.

**Comment by ajuric** [comment]
The line `Role "polyaxon" does not exist.` is old - that was when I was trying to upgrade from 0.6.0 to 0.6.1.

`django.db.utils.OperationalError: FATAL:  password authentication failed for user "polyaxon"` is that I get when trying to start fresh PLX 0.6.1.

**Comment by ajuric** [comment]
Ok, when I check the logs of postgresql in the fresh install PLX 0.6.1, there is also a line you mention `Role "polyaxon" does not exist.`

**Comment by ajuric** [comment]
I will open a new issue for this.
