### ISSUE TITLE
Deployment of v0.6.1 failure - password authentication failed for user "polyaxon"

### ISSUE THREAD

**Issue by ajuric** [polyaxon/polyaxon#722]
### Describe the bug

During the deployment of fresh (no old data) v0.6.1 PLX there are problems with Postgresql DB. In `polyaxon-sync-db` pod, there is an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "polyaxon"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "polyaxon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "polyaxon"
```

Also, in the `polyaxon-postgres-0` pod there are errors saying:
```
Role "polyaxon" does not exist.
```

I have also mentioned it [here](https://github.com/polyaxon/polyaxon/issues/709)

### To Reproduce

Deploy v0.6.1. PLX (`helm install polyaxon ...`) with no old data.

### Expected behavior

The new PLX should start normally with new DB (there is no DB migration needed because this is not an upgrade ...).

### Environment

 Kubeadm v1.11.1
Ubuntu 16.04
Docker 18.06.1-ce

**Comment by mouradmourafiq** [comment]
This is very strange case, following my last comment, did you try to deploy without postgres persistence?

**Comment by ajuric** [comment]
I have deployed now without postgres persistence, and it was successful.

**Comment by ajuric** [comment]
Here are the logs of **postgres without persistence**:
```
postgresql 09:45:23.47 
postgresql 09:45:23.47 Welcome to the Bitnami postgresql container
postgresql 09:45:23.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 09:45:23.48 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 09:45:23.48 Send us your feedback at containers@bitnami.com
postgresql 09:45:23.48 
postgresql 09:45:23.50 INFO  ==> ** Starting PostgreSQL setup **
postgresql 09:45:23.57 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 09:45:23.57 INFO  ==> Loading custom pre-init scripts...
postgresql 09:45:23.58 INFO  ==> Initializing PostgreSQL database...
postgresql 09:45:23.59 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 09:45:23.61 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 09:45:23.61 INFO  ==> Generating local authentication configuration
postgresql 09:45:24.56 INFO  ==> Starting PostgreSQL in background...
postgresql 09:45:24.96 INFO  ==> Creating user polyaxon
postgresql 09:45:24.98 INFO  ==> Grating access to "polyaxon" to the database "polyaxon"
postgresql 09:45:25.00 INFO  ==> Configuring replication parameters
postgresql 09:45:25.02 INFO  ==> Configuring fsync
postgresql 09:45:25.03 INFO  ==> Loading custom scripts...
postgresql 09:45:25.04 INFO  ==> Enabling remote connections
postgresql 09:45:25.05 INFO  ==> Stopping PostgreSQL...
postgresql 09:45:26.06 INFO  ==> ** PostgreSQL setup finished! **

postgresql 09:45:26.12 INFO  ==> ** Starting PostgreSQL **
2020-04-22 09:45:26.148 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-04-22 09:45:26.148 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-04-22 09:45:26.155 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-04-22 09:45:26.173 GMT [214] LOG:  database system was shut down at 2020-04-22 09:45:25 GMT
2020-04-22 09:45:26.179 GMT [1] LOG:  database system is ready to accept connections
```

It says that it created `polyaxon` user ...



Here are the logs of **postgres with persistence**:
```
postgresql 10:08:02.77 
postgresql 10:08:02.77 Welcome to the Bitnami postgresql container
postgresql 10:08:02.78 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 10:08:02.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 10:08:02.78 Send us your feedback at containers@bitnami.com
postgresql 10:08:02.78 
postgresql 10:08:02.79 INFO  ==> ** Starting PostgreSQL setup **
postgresql 10:08:02.82 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 10:08:02.83 INFO  ==> Loading custom pre-init scripts...
postgresql 10:08:02.83 INFO  ==> Initializing PostgreSQL database...
postgresql 10:08:02.83 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql 10:08:02.84 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 10:08:02.85 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 10:08:02.85 INFO  ==> Generating local authentication configuration
postgresql 10:08:02.85 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 10:08:02.86 INFO  ==> Configuring replication parameters
postgresql 10:08:02.87 INFO  ==> Configuring fsync
postgresql 10:08:02.91 INFO  ==> Loading custom scripts...
postgresql 10:08:02.91 INFO  ==> Enabling remote connections
postgresql 10:08:02.92 INFO  ==> Stopping PostgreSQL...
postgresql 10:08:02.92 INFO  ==> ** PostgreSQL setup finished! **

postgresql 10:08:02.95 INFO  ==> ** Starting PostgreSQL **
2020-04-22 10:08:03.056 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-04-22 10:08:03.056 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-04-22 10:08:03.105 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-04-22 10:08:03.381 GMT [170] LOG:  database system was interrupted; last known up at 2020-04-22 10:07:54 GMT
2020-04-22 10:08:04.816 GMT [170] LOG:  database system was not properly shut down; automatic recovery in progress
2020-04-22 10:08:04.888 GMT [170] LOG:  redo starts at 0/1657F90
2020-04-22 10:08:04.888 GMT [170] LOG:  invalid record length at 0/1658050: wanted 24, got 0
2020-04-22 10:08:04.888 GMT [170] LOG:  redo done at 0/1657FC8
2020-04-22 10:08:05.164 GMT [1] LOG:  database system is ready to accept connections
2020-04-22 10:08:13.811 GMT [184] FATAL:  password authentication failed for user "polyaxon"
2020-04-22 10:08:13.811 GMT [184] DETAIL:  Role "polyaxon" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"

```

It doesn't create `polyaxon` user ... ?

**Comment by ajuric** [comment]
The difference from the logs is this:

Without persistence:
```
postgresql 09:45:24.56 INFO  ==> Starting PostgreSQL in background...
postgresql 09:45:24.96 INFO  ==> Creating user polyaxon
postgresql 09:45:24.98 INFO  ==> Grating access to "polyaxon" to the database "polyaxon"
```

With persistence:
```
postgresql 10:08:02.85 INFO  ==> Deploying PostgreSQL with persisted data...
```

Does this suggest that it thinks there is some old data which it tries to reuse?
Because there are no old data: every time before deploying I delete the old postgres data directory and create a new empty one ...

**Comment by mouradmourafiq** [comment]
>  every time before deploying I delete the old postgres data directory and create a new empty one

There's definetely some meta data being loaded every time postgres is being deployed, not sure where the indexes and metadata is being saved, you will find more information if you check the official helm chart to verify what's happening.

> every time before deploying I delete the old postgres data directory and create a new empty one

I am not sure what delete means in your case, do you also delete hidden folders as well, does the chart only save data to the folder you mount in the PVC, or does it also load a an empty dir that gets persisted on the node and you are deploying postgres on the same node everytime, ...
Unfortunately I don't think you will get an answer here, you will probably get more accurate answers on the postgres forum to verify that you effectively delete all postgres data.

I will close the issue and I hope you will be able to solve the problem.

**Comment by ajuric** [comment]
Ok, thank you for help! I will try to search there.

Just to mention what it means "every time before deploying I delete the old postgres data":

I do `rm -rf polyaxon-storage` and `polyaxon-storage` contains all dirs needed by pvc-s (logs, outputs, postgresql, ...), and then recreate all these directories so that they are empty. So there is definetly no metadata being loaded.

Also, I do `kubeadm reset ...` and all that ...

It is deployed to same node every time.
