### ISSUE TITLE
Experiment stuck on building status

### ISSUE THREAD

**Issue by gzcf** [polyaxon/polyaxon#76]
My experiment stuck on building status. I checked logs, found that image was built and tagged successfully, but was not pushed to registry.

```
(polyaxon) gzc@ubuntu:~$ tail -n 3 /logs/root/cifar10/independents/3
2018-03-28 03:16:31,591 INFO {'aux': {'ID': 'sha256:eca15e3fdea00dbe5cc4367c8134d99197e193e3bb72a58049da845e81384b63'}}
2018-03-28 03:16:31,690 INFO {'stream': 'Successfully built eca15e3fdea0\n'}
2018-03-28 03:16:31,821 INFO {'stream': 'Successfully tagged 10.109.14.143:5000/cifar10:2873c5f4e75e08f3a719f43a8dd8373370822a51\n'}
```

I am using Polyaxon on minikube with none vm driver on ubuntu.

minikube start command

```
sudo minikube start --vm-driver=none --feature-gates=Accelerators=true
```
 
config.yaml

```
polyaxonSecret: "RANDOM_STRING"

user:
  username: "root"
  email: "root@polyaxon.local"
  password: "hello%1234"

isMinikube: true

rbac:
  enabled: false

ingress:
  enabled: false
serviceType: LoadBalancer

dirs:
  nvidia:
    lib: '/usr/lib/nvidia-375'
    bin: '/usr/lib/nvidia-375/bin'
    libcuda: '/usr/lib/x86_64-linux-gnu/libcuda.so.1'
```

polyaxon version: 0.0.6
kubernetes version: 1.8.0

I suspect there may be a network issue. But I don't know how to investigate deeper.

**Comment by mouradmourafiq** [comment]
hi @gzcf, was this the only experiment with this issue or did you experience the same thing when running other experiments?

**Comment by gzcf** [comment]
Experienced the same thing when running other experiments. I was trying stop and re-run without luck.

**Comment by mouradmourafiq** [comment]
Can you share your `polyaxonfile.yml`

**Comment by gzcf** [comment]
I was using `polyaxonfile_gpu.yml` and `polyaxonfile.yml` in `polyaxon-examples/tensorflow/cifare10`

**Comment by mouradmourafiq** [comment]
This is weird indeed, I just retried the `polyaxonfile.yml` in `polyaxon-examples/tensorflow/cifare10` on minikube and it went through.

Can you check that you can curl `10.109.14.143:5000` from the worker pod `kubectl exec -it -n polyaxon [NAME OF THE WORKER POD] -- bash` you might need to install curl `apt-get install -y curl`

**Comment by gzcf** [comment]
It's Ok to curl registry.

```
(polyaxon) gzc@ubuntu:~/polyaxon-quick-start$ kubectl -n polyaxon exec -it polyaxon-polyaxon-workers-6bcc45fd6-pnnq7 -- bash
root@polyaxon-polyaxon-workers-6bcc45fd6-pnnq7:/polyaxon/polyaxon# apt-get install -y curl
root@polyaxon-polyaxon-workers-6bcc45fd6-pnnq7:/polyaxon/polyaxon# curl -i 10.110.114.49:5000
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Fri, 30 Mar 2018 10:06:26 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

I re-deployed kubernetes and polyaxon, so registry ip change to 10.110.114.49 in commands.

**Comment by gzcf** [comment]
@mouradmourafiq 
I found error logs in scheduler which should be related to this issue.

```
[2018-03-30 09:55:42,522: INFO/MainProcess] Received task: experiments_build[428f2a49-85a9-4426-9162-a69a558eb37a]  ETA:[2018-03-30 09:55:43.519170+00:00] 
[2018-03-30 09:55:45,583: ERROR/ForkPoolWorker-2] Failed to connect to registry 500 Server Error: Internal Server Error ("Get https://10.110.114.49:5000/v2/: http: server gave HTTP response to HTTPS client")
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 222, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.32/auth
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
  File "/polyaxon/polyaxon/dockerizer/builders/base.py", line 81, in login
    reauth=True)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/daemon.py", line 148, in login
    return self._result(response, json=True)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 228, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://10.110.114.49:5000/v2/: http: server gave HTTP response to HTTPS client")
INFO 2018-03-30 09:55:45,904 publisher 46 140555875227392 Publishing log event for task: None.None, root.quick-start.1
[2018-03-30 09:55:45,904: INFO/ForkPoolWorker-2] Publishing log event for task: None.None, root.quick-start.1
...
publishing log event repeatedly
...
[2018-03-30 09:59:40,946: ERROR/ForkPoolWorker-2] Get https://10.110.114.49:5000/v2/: http: server gave HTTP response to HTTPS client
[2018-03-30 09:59:40,952: INFO/ForkPoolWorker-2] Celery task succeeded
[2018-03-30 09:59:40,952: INFO/ForkPoolWorker-2] Task experiments_build[428f2a49-85a9-4426-9162-a69a558eb37a] succeeded in 236.61640800908208s: None
```

It said "Failed to connect to registry". Do you know how to solve this?

**Comment by gzcf** [comment]
Solve it!

To be clear, this time I don't use minikube.

Configure "10.110.114.49:5000" as "insecure-registries" in my host's docker, and then it works.

add this config to `/etc/docker/daemon.json`

```
{
  "insecure-registries":["10.110.114.49:5000"]
}
```

and restart docker

```
sudo systemctl restart docker.service
```

**Comment by i4never** [comment]
@gzcf 
Same problem. I think the build process is successful but image pulling isn't. This workaround doesn't fit me because my kubernetes is on AWS and so I can't solve this by add config to `/etc/docker/deamon.json`. Is there any other method to solve this?

**Comment by mouradmourafiq** [comment]
I just made a fix for this issue and it will be part of the next release. You won't need to change `/etc/docker/daemon.json` it should work automatically.

**Comment by gzcf** [comment]
@mouradmourafiq Great! Could you explain a little about what is the root cause and how you fix it? I saw your code and didn't figure it out.
