### ISSUE TITLE
polyaxon-api pod not deployed with external postgresql

### ISSUE THREAD

**Issue by yigitsoy** [polyaxon/polyaxon#776]
### Describe the bug
Polyaxon API pod in 0.6.1 does not seem to communicate with the external PostgreSQL database.

### To Reproduce
I installed polyaxon using
```bash
helm install polyaxon/polyaxon --name=polyaxon --namespace=polyaxon -f polyaxon-config.yml --wait --debug --timeout 3000
```

where polyaxon-config.yml is 

```yaml
namespace: polyaxon
deploymentType: kubernetes
serviceType: NodePort
user:
  username: root
  email: root@example.com
  password: 
limitResources: false
api:
  replicas: 1
  

timeZone: CET

persistence:
  logs:
    existingClaim: polyaxon-logs
    mountPath: /logs
  repos:
    existingClaim: polyaxon-repos
    mountPath: /repos
  upload:
    existingClaim: polyaxon-upload
    mountPath: /upload
  data:
    data-original:
      existingClaim: polyaxon-data-original
      mountPath: /data/original
      readOnly: true
    data-work:
      existingClaim: polyaxon-data-work
      mountPath: /data/work
      readOnly: true
    # we add the time zones here in order to have the host time-zone available in dockers
    tz1:
      mountPath: "/etc/timezone"
      hostPath: "/etc/timezone"
      readOnly: true
    tz2:
      mountPath: "/etc/localtime"
      hostPath: "/etc/localtime"
      readOnly: true
  outputs:
    outputs1:
      existingClaim: polyaxon-outputs1
      readOnly: false
      mountPath: /outputs

docker-registry:
  persistence:
    enabled: true
    existingClaim: polyaxon-registry

redis:
  master:
    persistence:
      enabled: true
  persistence:
    enabled: true
    existingClaim: polyaxon-redis
  slave:
    persistence:
      enabled: false

postgresql:
  enabled: false

externalServices:
  postgresql:
    user: polyaxon
    password: polyaxon
    database: polyaxon
    host: 192.168.168.126:5432

```

kubectl cluster-info
```bash
Kubernetes master is running at https://192.168.168.151:6443 
KubeDNS is running at https://192.168.168.151:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
 ```

kubectl get pods --all-namespaces                                                                                                                                         
 ```bash
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE
kube-system   coredns-66bff467f8-v9xlm                       1/1     Running   1          5d16h
kube-system   coredns-66bff467f8-wfmnc                       1/1     Running   1          5d16h
kube-system   etcd-kmle-muc-pa-master                        1/1     Running   4          5d16h
kube-system   kube-apiserver-kmle-muc-pa-master              1/1     Running   14         5d16h
kube-system   kube-controller-manager-kmle-muc-pa-master     1/1     Running   114        5d16h
kube-system   kube-flannel-ds-amd64-t5h8t                    1/1     Running   1          5d16h
kube-system   kube-proxy-kms2d                               1/1     Running   1          5d16h
kube-system   kube-scheduler-kmle-muc-pa-master              1/1     Running   114        5d16h
kube-system   nvidia-device-plugin-daemonset-l7z2g           1/1     Running   1          5d16h
kube-system   tiller-deploy-66fccb9847-zcxgn                 1/1     Running   1          21h
polyaxon      polyaxon-docker-registry-69c8c67467-rw4t2      1/1     Running   0          27m
polyaxon      polyaxon-polyaxon-api-846f48db4b-szm92         0/2     Running   6          27m
polyaxon      polyaxon-polyaxon-beat-6d47c44b7c-tfdd8        2/2     Running   0          27m
polyaxon      polyaxon-polyaxon-events-5676cccb5f-tpgjc      1/1     Running   0          27m
polyaxon      polyaxon-polyaxon-hpsearch-6ffb756db7-9hl64    1/1     Running   0          27m
polyaxon      polyaxon-polyaxon-k8s-events-54c5888bb-hfxz6   1/1     Running   0          27m
polyaxon      polyaxon-polyaxon-monitors-fb767679c-fzq26     1/1     Running   0          27m
polyaxon      polyaxon-polyaxon-scheduler-cbbd87c8f-7t8hx    1/1     Running   0          27m
polyaxon      polyaxon-rabbitmq-ha-0                         1/1     Running   0          27m
polyaxon      polyaxon-redis-master-0                        1/1     Running   0          27m
polyaxon      polyaxon-redis-slave-0                         1/1     Running   0          27m
polyaxon      polyaxon-redis-slave-1                         1/1     Running   0          25m
 ```
 
kubectl logs tiller-deploy-66fccb9847-zcxgn -n kube-system
 
```bash
[tiller] 2020/05/20 07:05:17 preparing install for polyaxon
[storage] 2020/05/20 07:05:17 getting release history for "polyaxon"
[tiller] 2020/05/20 07:05:17 rendering polyaxon chart using values
2020/05/20 07:05:17 info: manifest "polyaxon/charts/rabbitmq-ha/templates/pdb.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/templates/ing.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/rabbitmq-ha/templates/ingress.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/metrics-prometheus.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/psp.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/templates/hooks/load-fixtures-job.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/docker-registry/templates/pvc.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/docker-registry/templates/poddisruptionbudget.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/redis-with-sentinel-svc.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/templates/hooks/tables-job.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/rabbitmq-ha/templates/servicemonitor.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/templates/resources-ds.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/networkpolicy.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/redis-rolebinding.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/rabbitmq-ha/templates/alerts.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/secret.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/metrics-svc.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/redis-serviceaccount.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/docker-registry/templates/ingress.yaml" is empty. Skipping.
2020/05/20 07:05:17 info: manifest "polyaxon/charts/redis/templates/redis-role.yaml" is empty. Skipping.
[tiller] 2020/05/20 07:05:17 performing install for polyaxon
[tiller] 2020/05/20 07:05:17 executing 6 crd-install hooks for polyaxon
[tiller] 2020/05/20 07:05:17 hooks complete for crd-install polyaxon
[tiller] 2020/05/20 07:05:17 executing 6 pre-install hooks for polyaxon
[tiller] 2020/05/20 07:05:17 hooks complete for pre-install polyaxon
[storage] 2020/05/20 07:05:17 getting release history for "polyaxon"
[storage] 2020/05/20 07:05:17 creating release "polyaxon.v1"
[kube] 2020/05/20 07:05:17 building resources from manifest
[kube] 2020/05/20 07:05:17 creating 38 resource(s)
[kube] 2020/05/20 07:05:17 beginning wait for 38 resources with timeout of 50m0s
[kube] 2020/05/20 07:06:54 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:06:57 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:04 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:11 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:16 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:19 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:22 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:25 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:29 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:32 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:35 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:38 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:41 Pod is not ready: polyaxon/polyaxon-rabbitmq-ha-0
[kube] 2020/05/20 07:07:45 Pod is not ready: polyaxon/polyaxon-redis-slave-0
[kube] 2020/05/20 07:07:48 Pod is not ready: polyaxon/polyaxon-redis-slave-0
[kube] 2020/05/20 07:07:51 Pod is not ready: polyaxon/polyaxon-redis-slave-1
[kube] 2020/05/20 07:07:54 Pod is not ready: polyaxon/polyaxon-redis-slave-1
[kube] 2020/05/20 07:07:57 Pod is not ready: polyaxon/polyaxon-redis-slave-1
[kube] 2020/05/20 07:08:01 Pod is not ready: polyaxon/polyaxon-redis-slave-1
[kube] 2020/05/20 07:08:04 Deployment is not ready: polyaxon/polyaxon-polyaxon-api
[kube] 2020/05/20 07:08:07 Deployment is not ready: polyaxon/polyaxon-polyaxon-api
[kube] 2020/05/20 07:08:10 Deployment is not ready: polyaxon/polyaxon-polyaxon-api
…. (this goes on like this as long as –timeout..)
 ```

kubectl describe pod -n polyaxon polyaxon-polyaxon-api-846f48db4b-szm92
 
```bash
Name:         polyaxon-polyaxon-api-846f48db4b-szm92
Namespace:    polyaxon
Priority:     0
Node:         kmle-muc-pa-master/192.168.168.151
Start Time:   Wed, 20 May 2020 07:06:07 +0000
Labels:       app=polyaxon-polyaxon-api
              app.kubernetes.io/instance=polyaxon
              app.kubernetes.io/name=polyaxon-polyaxon-api
              pod-template-hash=846f48db4b
              release=polyaxon
              role=polyaxon-api
              type=polyaxon-core
Annotations:  chart: polyaxon-0.6.1
              checksum/config: 84d06b1224edb0b69c08812851a567aeb149470a6a5704770627f945916679e8
              checksum/secrets: b0e81ecab2be9b95b61f30d1cd026aee1af0e0afbd8907c0d5bf3d9ddd944e55
Status:       Running
IP:           10.244.0.146
IPs:
  IP:           10.244.0.146
Controlled By:  ReplicaSet/polyaxon-polyaxon-api-846f48db4b
Containers:
  polyaxon-api:
    Container ID:   docker://d1ef0a3a441c93d5150eb68a80493f147ddf7737d01015f42bbc086317474234
    Image:          polyaxon/polyaxon-api:0.6.1
    Image ID:       docker-pullable://polyaxon/polyaxon-api@sha256:e44b576bd1240b4ca992d6610ec52e6a3bfd75c169f71cd6b42059e6e00f04e5
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 20 May 2020 07:31:50 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 20 May 2020 07:23:47 +0000
      Finished:     Wed, 20 May 2020 07:31:45 +0000
    Ready:          False
    Restart Count:  3
    Requests:
      cpu:      128m
      memory:   300Mi
    Liveness:   http-get http://:80/healthz/ delay=150s timeout=2s period=30s #success=1 #failure=10
    Readiness:  http-get http://:80/healthz/ delay=150s timeout=2s period=30s #success=1 #failure=30
    Environment Variables from:
      polyaxon-polyaxon-config  ConfigMap  Optional: false
      polyaxon-polyaxon-secret  Secret     Optional: false
    Environment:
      POLYAXON_K8S_NODE_NAME:         (v1:spec.nodeName)
      POLYAXON_RABBITMQ_PASSWORD:    <set to the key 'rabbitmq-password' in secret 'polyaxon-rabbitmq-ha'>                   Optional: false
      POLYAXON_DB_PASSWORD:          <set to the key 'postgresql-password' in secret 'polyaxon-polyaxon-postgresql-secret'>  Optional: false
      POLYAXON_PERSISTENCE_OUTPUTS:  {"outputs1":{"existingClaim":"polyaxon-outputs1","mountPath":"/outputs","readOnly":false}}
      POLYAXON_PERSISTENCE_DATA:     {"data-original":{"existingClaim":"polyaxon-data-original","mountPath":"/data/original","readOnly":true},"data-work":{"existingClaim":"polyaxon-data-work","mountPath":"/data/work","readOnly":true},"tz1":{"hostPath":"/etc/timezone","mountPath":"/etc/timezone","readOnly":true},"tz2":{"hostPath":"/etc/localtime","mountPath":"/etc/localtime","readOnly":true}}
      POLYAXON_PERSISTENCE_LOGS:     {"existingClaim":"polyaxon-logs","hostPath":"/tmp/logs","mountPath":"/logs"}
      POLYAXON_PERSISTENCE_UPLOAD:   {"existingClaim":"polyaxon-upload","hostPath":"/tmp/upload","mountPath":"/upload"}
      POLYAXON_PERSISTENCE_REPOS:    {"existingClaim":"polyaxon-repos","hostPath":"/tmp/repos","mountPath":"/repos"}
    Mounts:
      /logs from logs (rw)
      /outputs from outputs1 (rw)
      /repos from repos (rw)
      /upload from upload (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from polyaxon-polyaxon-serviceaccount-token-rzf7l (ro)
  polyaxon-streams:
    Container ID:   docker://596ad14e52616792ce5c614ed3f639930504c03b076e8c074b91b8c9fde2e0cc
    Image:          polyaxon/polyaxon-streams:0.6.1
    Image ID:       docker-pullable://polyaxon/polyaxon-streams@sha256:6ff8cadd3ecc1092568231528ae5afbff582a3bdc2c06fba4b685d37ee674ea3
    Port:           1337/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 20 May 2020 07:28:32 +0000
    Ready:          False
    Restart Count:  3
    Requests:
      cpu:      100m
      memory:   128Mi
    Liveness:   http-get http://:1337/healthz/ delay=100s timeout=2s period=30s #success=1 #failure=10
    Readiness:  http-get http://:1337/healthz/ delay=150s timeout=2s period=30s #success=1 #failure=30
    Environment Variables from:
      polyaxon-polyaxon-config  ConfigMap  Optional: false
      polyaxon-polyaxon-secret  Secret     Optional: false
    Environment:
      POLYAXON_K8S_NODE_NAME:       (v1:spec.nodeName)
      POLYAXON_RABBITMQ_PASSWORD:  <set to the key 'rabbitmq-password' in secret 'polyaxon-rabbitmq-ha'>                   Optional: false
      POLYAXON_DB_PASSWORD:        <set to the key 'postgresql-password' in secret 'polyaxon-polyaxon-postgresql-secret'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from polyaxon-polyaxon-serviceaccount-token-rzf7l (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  logs:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  polyaxon-logs
    ReadOnly:   false
  outputs1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  polyaxon-outputs1
    ReadOnly:   false
  repos:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  polyaxon-repos
    ReadOnly:   false
  upload:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  polyaxon-upload
    ReadOnly:   false
  polyaxon-polyaxon-serviceaccount-token-rzf7l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  polyaxon-polyaxon-serviceaccount-token-rzf7l
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                         Message
  ----     ------     ----                  ----                         -------
  Normal   Scheduled  <unknown>             default-scheduler            Successfully assigned polyaxon/polyaxon-polyaxon-api-846f48db4b-szm92 to kmle-muc-pa-master
  Normal   Pulling    28m                   kubelet, kmle-muc-pa-master  Pulling image "polyaxon/polyaxon-api:0.6.1"
  Normal   Pulled     28m                   kubelet, kmle-muc-pa-master  Successfully pulled image "polyaxon/polyaxon-api:0.6.1"
  Normal   Created    28m                   kubelet, kmle-muc-pa-master  Created container polyaxon-api
  Normal   Started    28m                   kubelet, kmle-muc-pa-master  Started container polyaxon-api
  Normal   Pulling    28m                   kubelet, kmle-muc-pa-master  Pulling image "polyaxon/polyaxon-streams:0.6.1"
  Normal   Pulled     28m                   kubelet, kmle-muc-pa-master  Successfully pulled image "polyaxon/polyaxon-streams:0.6.1"
  Normal   Created    28m                   kubelet, kmle-muc-pa-master  Created container polyaxon-streams
  Normal   Started    28m                   kubelet, kmle-muc-pa-master  Started container polyaxon-streams
  Warning  Unhealthy  24m (x4 over 25m)     kubelet, kmle-muc-pa-master  Readiness probe failed: Get http://10.244.0.146:80/healthz/: dial tcp 10.244.0.146:80: connect: connection refused
  Warning  Unhealthy  24m (x4 over 25m)     kubelet, kmle-muc-pa-master  Readiness probe failed: Get http://10.244.0.146:1337/healthz/: dial tcp 10.244.0.146:1337: connect: connection refused
  Warning  Unhealthy  8m34s (x22 over 25m)  kubelet, kmle-muc-pa-master  Liveness probe failed: Get http://10.244.0.146:80/healthz/: dial tcp 10.244.0.146:80: connect: connection refused
  Warning  Unhealthy  3m22s (x35 over 26m)  kubelet, kmle-muc-pa-master  Liveness probe failed: Get http://10.244.0.146:1337/healthz/: dial tcp 10.244.0.146:1337: connect: connection refused
 ```
 
 
kubectl logs -n polyaxon polyaxon-polyaxon-api-846f48db4b-szm92 -c polyaxon-api
```bash
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
 ```

kubectl logs -n polyaxon polyaxon-polyaxon-api-846f48db4b-szm92 -c polyaxon-streams

```bash
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
 ```
 
 
 
 
This all happens if I omit the port number to PostgreSQL server. When I specify the postgresql like
 ```yaml
externalServices:
  postgresql:
    user: polyaxon
    password: polyaxon
    database: polyaxon
    host: 192.168.168.126:5432
 ```

I get the followings;
 
kubectl get pods --all-namespaces 

```bash 
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE
kube-system   coredns-66bff467f8-v9xlm                       1/1     Running   1          5d16h
kube-system   coredns-66bff467f8-wfmnc                       1/1     Running   1          5d16h
kube-system   etcd-kmle-muc-pa-master                        1/1     Running   4          5d16h
kube-system   kube-apiserver-kmle-muc-pa-master              1/1     Running   14         5d16h
kube-system   kube-controller-manager-kmle-muc-pa-master     1/1     Running   115        5d16h
kube-system   kube-flannel-ds-amd64-t5h8t                    1/1     Running   1          5d16h
kube-system   kube-proxy-kms2d                               1/1     Running   1          5d16h
kube-system   kube-scheduler-kmle-muc-pa-master              1/1     Running   115        5d16h
kube-system   nvidia-device-plugin-daemonset-l7z2g           1/1     Running   1          5d16h
kube-system   tiller-deploy-66fccb9847-zcxgn                 1/1     Running   1          21h
polyaxon      polyaxon-docker-registry-69c8c67467-fhkxp      1/1     Running   0          11m
polyaxon      polyaxon-polyaxon-api-7fd7589985-6pvwz         1/2     Running   1          11m
polyaxon      polyaxon-polyaxon-beat-7d849c555f-6dckk        2/2     Running   0          11m
polyaxon      polyaxon-polyaxon-events-74b787c8cc-82sq4      1/1     Running   0          11m
polyaxon      polyaxon-polyaxon-hpsearch-675c6df4c7-9b46t    1/1     Running   0          11m
polyaxon      polyaxon-polyaxon-k8s-events-7df5f4fdd-vgbx9   1/1     Running   0          11m
polyaxon      polyaxon-polyaxon-monitors-76b8cf6487-vq8k4    1/1     Running   0          11m
polyaxon      polyaxon-polyaxon-scheduler-784494c9cb-2shgg   1/1     Running   0          11m
polyaxon      polyaxon-rabbitmq-ha-0                         1/1     Running   0          11m
polyaxon      polyaxon-redis-master-0                        1/1     Running   0          11m
polyaxon      polyaxon-redis-slave-0                         1/1     Running   0          11m
polyaxon      polyaxon-redis-slave-1                         1/1     Running   0          10m
 ```

Nothing changes in tiller deploy pod logs.
 
kubectl logs -n polyaxon polyaxon-polyaxon-api-7fd7589985-6pvwz  -c polyaxon-streams
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "192.168.168.126:5432" to address: Name or service not known
 ```
 
The above exception was the direct cause of the following exception:
 
```bash
Traceback (most recent call last):
  File "/polyaxon/polyaxon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/showmigrations.py", line 46, in handle
    return self.show_plan(connection, options['app_label'])
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/showmigrations.py", line 103, in show_plan
    loader = MigrationLoader(connection)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "192.168.168.126:5432" to address: Name or service not known
 
Running...
 ```
kubectl logs -n polyaxon polyaxon-polyaxon-api-7fd7589985-6pvwz  -c polyaxon-api
 ```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "/polyaxon/web/../polyaxon/polyaxon/context_processors.py", line 11, in versions
    'cli_version': CliVersion.load(),
  File "/polyaxon/web/../polyaxon/db/models/versions.py", line 47, in load
    obj = cls.objects.get(pk=1)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
   self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "192.168.168.126:5432" to address: Name or service not known
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "192.168.168.126:5432" to address: Name or service not known
 ```
Finally, using 
 ```yaml
externalServices:
  postgresql:
    user: polyaxon
    password: polyaxon
    database: polyaxon
    host: 192.168.168.126
    port: 5432
 ```
leads to the initial problem of “Preparing…” status of both containers of api pod.
 
So it is clearly a connection issue to the DB server. From the host machine I can connect to the database without any problem with
 ```bash
psql -U polyaxon -p 5432 -h 192.168.168.126
 ```
It appears to be something to do with the pods/containers not being able to connect to the outside world. So, I tested it. Not being able to ping inside the docker container, I used this trick
 
kubectl exec -it -n polyaxon polyaxon-polyaxon-api-7fd7589985-6pvwz  -c polyaxon-streams -- bash
```bash
root@polyaxon-polyaxon-api-7fd7589985-6pvwz:/polyaxon# (echo >/dev/tcp/192.168.168.126/5432) &>/dev/null && echo "open" || echo "closed"
open
 ```
If I understood correctly, the pod/container can connect to the port of the host of the DB but the Django DB fails to recognize it. 
 
With some research, I read something about the DNS setting and providing core-dns as dns backend did not help.
 
kubectl get service --all-namespaces
```bash
NAMESPACE     NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                       AGE
default       kubernetes                       ClusterIP   10.96.0.1        <none>        443/TCP                       5d18h
kube-system   kube-dns                         ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP        5d18h
kube-system   tiller-deploy                    ClusterIP   10.110.7.192     <none>        44134/TCP                     5d18h
polyaxon      polyaxon-docker-registry         NodePort    10.101.108.155   <none>        5000:31813/TCP                34m
polyaxon      polyaxon-polyaxon-api            NodePort    10.106.53.104    <none>        80:31811/TCP                  34m
polyaxon      polyaxon-rabbitmq-ha             ClusterIP   10.96.35.65      <none>        15672/TCP,5672/TCP,4369/TCP   34m
polyaxon      polyaxon-rabbitmq-ha-discovery   ClusterIP   None             <none>        15672/TCP,5672/TCP,4369/TCP   34m
polyaxon      polyaxon-redis-headless          ClusterIP   None             <none>        6379/TCP                      34m
polyaxon      polyaxon-redis-master            ClusterIP   10.102.169.162   <none>        6379/TCP                      34m
polyaxon      polyaxon-redis-slave             ClusterIP   10.102.149.214   <none>        6379/TCP                      34m
```

### Expected behavior

polyaxon-api pod communicates with the provided PostgreSQL database and deploys successfully.

### Environment

```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
```bash
helm version
Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```

**Comment by mouradmourafiq** [comment]
From slack:

>it seems like you are setting the port on the host directly, can you use the [port: field](https://github.com/polyaxon/polyaxon-charts/blob/master/polyaxon/values.yaml#L242) and try.

Closing the issues. Seems like a bad configuration.

**Comment by mouradmourafiq** [comment]
Where is the db deployed? can you share a bit more info about your cluster?

**Comment by yigitsoy** [comment]
Please see the slack thread.

**Comment by mouradmourafiq** [comment]
Reason:

> Hi Mourad, an update from my side; it finally worked after reverting rbac and ingress  to default values. Thanks a lot for your help!
